### ISSUE TITLE
[SCAN]  CVE Database has not been updated for 11 days

### ISSUE THREAD

**Issue by lindhe** [neuvector/neuvector#1105]
**Environment**
Platform: Rancher
Kubernetes/Platform Version(s): Rancher v2.7.6, Kubernetes v1.26.8

**Describe the bug**

I just noticed a warning in our NeuVector dashboard that the CVE database has not been updated for 11 days:

<img width="254" alt="CVE Database has not been updated for 11 days" src="https://github.com/neuvector/neuvector/assets/7773090/206de644-521f-4058-91e3-211bd6c2c567">

After investigating, I found that this is not really our fault. Turns out that the Scanner images on GitHub has not been updated for 11 days. Is this normal, or has something broken in your release pipeline?

**To Reproduce**

1. Install NeuVector 11 days ago.
2. Wait until today.

**Expected behavior**

I would have expected the scanner component to be updated at least as frequently as NeuVector expects it to (so I do not get a warning).

**Screenshots**

![NeuVector Scanner image tags on DockerHub](https://github.com/neuvector/neuvector/assets/7773090/e4df0caf-399d-45c8-9237-6b878f00de4b)

**Additional context**

https://hub.docker.com/r/neuvector/scanner/tags

**Comment by michbeck100** [comment]
is fixed for me. Latest image tag is from 17 hours ago. https://hub.docker.com/r/rancher/mirrored-neuvector-scanner/tags

**Comment by lindhe** [comment]
Yep. Thanks for noticing.

Before marking this as closed, it would still be nice to know if this was a fluke that we can ignore or if the threshold for old databases should be increased.

**Comment by becitsthere** [comment]
This was caused by the syntax change of one of security feeds. It has been resolved.
