### ISSUE TITLE
Scanner not working - ERRO|SCN|main.(*Tasker).Run: Done - error=exit status 2

### ISSUE THREAD

**Issue by smangelkramer** [neuvector/neuvector#117]
**Environment**
Platform: Rancher v2.6.3
Kubernetes/Platform Version(s): RKE 2 (v1.21.9+rke2r1)
OS: SLES 15 SP3
NeuVector: 5.0.0-preview.2 

**Describe the bug**
I installed NeuVector via Helm Chart and a private registry.
So far everything works quite well and all features of NeuVector works as expected with one exeption:
The scanner is not working.

All Pods are in "Running state" and everything looks good so far:

```
kubectl get pods -n neuvector
NAME                                        READY   STATUS    RESTARTS   AGE
neuvector-controller-pod-787578844b-p4nlw   1/1     Running   0          4m25s
neuvector-controller-pod-787578844b-tbzk4   1/1     Running   0          4m25s
neuvector-controller-pod-787578844b-xqtzw   1/1     Running   0          4m25s
neuvector-enforcer-pod-6gckg                1/1     Running   0          4m25s
neuvector-enforcer-pod-bdrph                1/1     Running   0          4m25s
neuvector-enforcer-pod-tl5g8                1/1     Running   0          4m25s
neuvector-manager-pod-6cf449ccdb-rrjxd      1/1     Running   0          4m25s
neuvector-scanner-pod-6487bdcb78-mfnl8      1/1     Running   0          4m25s
neuvector-scanner-pod-6487bdcb78-t5hrz      1/1     Running   0          4m25s
neuvector-scanner-pod-6487bdcb78-tkgmc      1/1     Running   0          4m25s
```

But when we try to start a scan, the scan fails.

Output of the scan logs is like:

```
2022-03-11T13:07:37.553|DEBU|SCN|main.(*rpcService).ScanAppPackage: - Packages=[AppName:"kubernetes" ModuleName:"kubernetes" Version:"1.21.9+rke2r1" FileName:"kubernetes" ]
2022-03-11T13:07:37.554|DEBU|SCN|main.(*Tasker).Run:
2022-03-11T13:07:37.555|DEBU|SCN|main.(*Tasker).Run: - args=[-t pkg -i /tmp/2a97687a-cedc-42bb-9df5-872adbf9334e_i.json -o /tmp/2a97687a-cedc-42bb-9df5-872adbf9334e_o.json] cmd=/usr/local/bin/scannerTask wpath=/tmp/images/2a97687a-cedc-42bb-9df5-872adbf9334e
2022-03-11T13:07:37.58 |INFO|SCT|system.NewSystemTools: cgroup v1
2022-03-11T13:07:37.58 |DEBU|SCT|main.main: - imageWorkingPath=/tmp/images/2a97687a-cedc-42bb-9df5-872adbf9334e
---usage: scannerTask [OPTIONS]
  -i string
    	input json name (default "input.json")
  -o string
    	output json name (default "result.json")
  -t string
    	scan type: reg, pkg, dat or awl (Required)
  -u string
    	Container socket URL
2022-03-11T13:07:37.583|ERRO|SCN|main.(*Tasker).Run: Done - error=exit status 2
```

**To Reproduce**

1. Install NeuVector
2. Start a Scan (f.e. to OCI Image or K8S Cluster)

**Expected behavior**

- A clear log / message pointing to the root cause.

**Comment by becitsthere** [comment]
Which scan did you do? There can be runtime scan of pod/node, scanning images in a registry or triggering scan using REST API.

**Comment by smangelkramer** [comment]
All types of scan did not work. I did the same setup with RKE1 (Docker) and Ubuntu 20.04 LTS, here all Scans works as expected.

Difference is OS and Container Runtime.
From my perspective I set all the correct sockets for containerd.

**Comment by smangelkramer** [comment]
@jayhuang-suse thank you for the update. With disabled apparmor the scanner is working.

**Comment by jayhuang-suse** [comment]
I am glad that you solve the situation. Can you provide the apparmor settings for our further study. Thanks.

**Comment by smangelkramer** [comment]
It's a "out of the box" default SLES 15 SP3 installation (i did with Packer) - would say: SLES 15SP3 default.

My `audit.log` looks like:

`type=AVC msg=audit(1647543148.161:99403): apparmor="DENIED" operation="ptrace" profile="cri-containerd.apparmor.d" pid=14528 comm="scannerTask" requested_mask="readby" denied_mask="readby" peer="cri-containerd.apparmor.d"`

**Comment by jayhuang-suse** [comment]
A PR is merged at https://github.com/neuvector/scanner/pull/18
