### ISSUE TITLE
Can NeuVector be installed on Kubernetes 1.15.5?

### ISSUE THREAD

**Issue by HPF1992** [neuvector/neuvector#1294]
I have installed NeuVector on Kubernetes 1.15.5, but it prompts that the CRD schema of nvsecurityrules.neuvector.comnvclustersecurityrules.neuvector.comnvadmissioncontrolsecurityrules.neuvnvdlpsecurityrules.neuvector.com, nvwafsecurityrules.neuvector.com, nvvulnerabilityprofiles.neuvector.com, nvcomplianceprofiles.neuvector.com is out of date.
Can I fix it?

**Comment by williamlin-suse** [comment]
https://open-docs.neuvector.com/basics/requirements
