### ISSUE TITLE
Neuvector images built for Apple aarm64

### ISSUE THREAD

**Issue by nycnewman** [neuvector/neuvector#131]
**Is your feature request related to a problem? Please describe.**

linux/arm64 images would allow local development / testing of Neuvector on Apple Mac M1 line of laptops and servers (i.e. Studio offers plenty of capacity)

**Describe the solution you'd like**

Publish an image for arm64 to Docker Hub or expose build system so others can build locally 

**Describe alternatives you've considered**

I have put in a support ticket for our commercial license and this is being considered by Product Team. Opens-sourcing of build tools might allow this happen faster.

**Additional context**

Not expecting this to be a production support configuration but local K8s development (KinD on Podman) offers reasonable local configuration for setup and testing.

**Comment by garyduan** [comment]
ARM CPU is not supported yet. We will add it to the roadmap based on the customer requests.
