### ISSUE TITLE
API not authenticating to full access token for scanning registry

### ISSUE THREAD

**Issue by tomatoonrye** [neuvector/neuvector#1320]
**Environment**
Platform: Kubernetes 

**Describe the bug**
When scanning a repository with an API token created in the UI, the token fails to authenticate. The appropriate variables are all defined. The script provided in the documentation authenticates fine when it is using a temp token created from the username password request, but the X-Auth-Token manually created does not. This is happening in an rke2 cluster, a load balancing service, and that is port forwarded to 10443.

`curl -vk -H "Content-Type: application/json" -H "X-Auth-Token: $_TOKEN_" -d '{"request": {"registry": "'https://registry.hub.docker.com'", "username": "'$_registryUsername_'", "password": "'$_registryPassword_'", "repository": "'mysql'", "tag": "'8.3.0'"}}' "https://localhost:10443/v1/scan/repository" >  scan_results.json`

**To Reproduce**
1. Create API Token in neuvector running in RKE2
2. Create the API service
3. Port forward the service to 10443
4. Use the API token

**Expected behavior**
Given all the correct variables, this command should return a scan report in json format of mysql:8.3.0 from docker hub. Different behavior from the max privilege api token is not expected compared to the temp token in the documentation script.

**Screenshots**
Screenshot A is the request with the temp token
![Screenshot 2024-05-01 at 17 50 23](https://github.com/neuvector/neuvector/assets/168683135/25af29e5-7be4-46a3-b06f-131f7085ee4a)

Screenshot B is the request with the full access token from the UI
![Screenshot 2024-05-01 at 17 49 40](https://github.com/neuvector/neuvector/assets/168683135/e95e550a-86b9-43bc-820d-d0cf8c2c26f4)

**Comment by williamlin-suse** [comment]
How did you create API token in NV UI?

**Comment by tomatoonrye** [comment]
As admin, expires in 1 year, and with global role as admin. It works for other API calls such as v1/scan/workload/$_containerid_

**Comment by williamlin-suse** [comment]
Do you mean API key? There is no way to create API token in NV UI.

**Comment by tomatoonrye** [comment]
Yes, sorry. Api key and I'm using the X-Auth-Token from that

**Comment by tomatoonrye** [comment]
Ok, looks like when extracting from the script, I was using the wrong header in X-Auth-Token instead of X-Auth-Apikey

`curl -k -H "Content-Type: application/xml" -H "X-Auth-Apikey: $_TOKEN_" -d '{"request": {"registry": "'$_registryURL_'", "username": "'$_registryUsername_'", "password": "'$_registryPassword_'", "repository": "'mysql'", "tag": "'$_tag_'"}}' "https://$_controllerIP_:$_controllerRESTAPIPort_/v1/scan/repository" > /dev/null 2>&1 > foo.json`

**Comment by tomatoonrye** [comment]
Thank you William
