### ISSUE TITLE
Works as designed? Admin user password not changed by Secret/ConfigMap if already changed before

### ISSUE THREAD

**Issue by wombelix** [neuvector/neuvector#1389]
**Environment**
Platform: Amazon EKS
Kubernetes/Platform Version(s): v1.29.1

**Describe the bug**
For me it feels like a bug or let's say the behavior isn't what I've expected based on the documentation.

I create a `Secret` that contains `userinitcfg.yaml` to set a new admin password as described in https://open-docs.neuvector.com/deploying/production/configmap/.
I want to manage the admin password only through that `Secret`, not manually.
If the admin password was changed manually, or during a previous cluster start when the config was applied, it's not possible to update it through the init config again.
If I change the `Secret`, I will see the error `ERRO|CTL|rest.updateAdminPass: already updated - Password of=admin` next time when the controller loads the config. The changed admin password will not be applied.

It boils down to this line https://github.com/neuvector/neuvector/blob/main/controller/rest/configmap.go#L427 which is triggered from here https://github.com/neuvector/neuvector/blob/main/controller/cluster.go#L134 when a controller becomes Leader.
Independent if `always_reload` is set to `true` (that's only taken into account way earlier in the process https://github.com/neuvector/neuvector/blob/main/controller/rest/configmap.go#L852), the admin password will never be changed if the current hash already differs from the default password hash.

**To Reproduce**
1. Create a `Secret` or `ConfigMap` to set the admin password (https://open-docs.neuvector.com/deploying/production/configmap/)
2. Verify that the initial admin password was replaced by the one from the init config or change it manually
3. Change the admin password inside the `Secret`/`ConfigMap`
4. Restart the controller (e.g. by restarting the neuvector-controller-pod deployment)
5. The password is unchanged and the logs (from the elected leader pod) show `ERRO|CTL|rest.updateAdminPass: already updated - Password of=admin`.

**Expected behavior**
When I use a init config to configure my users, including the admin user, I expect that the password in NeuVector changes when I adjust the init config. I don't see a limitation mentioned in the documentation. The value `always_reload` gives me the impression that updated passwords should always be applied when the controller starts.

**Screenshots**
n/a

**UI Issue**
n/a

**Additional context**
My use-case: I want to manage credentials outside the Cluster. I use `ExternalSecrets` to sync them from AWS KMS. I want NeuVector to be fully managed via code, including the password of any local user. Settings done via init config or CRDs should always have precedence over manually performed changes / the current state inside the cluster.

**Comment by williamlin-suse** [comment]
You need to set  always_reload  to true in the configmap.
When the next controller starts, it sees always_reload=true so that it resets admin's password based on the value specified in userinitcfg.yaml if the password meets the requirement defined by password profile

**Comment by wombelix** [comment]
> You need to set always_reload to true in the configmap. When the next controller starts, it sees always_reload=true so that it resets admin's password based on the value specified in userinitcfg.yaml if the password meets the requirement defined by password profile

`always_reload` is set to true and works for anything but not the admin password. If you try to change it a second time that way your get the error message I shared. From a look into the code it seems that the admin password is handled differently than from any other user.

**Comment by williamlin-suse** [comment]
In our testing as long as always_reload=true, the new controller always resets admin's password based on the value specified in userinitcfg.yaml if the password meets the requirement defined by password profile.

**Comment by wombelix** [comment]
> In our testing as long as always_reload=true, the new controller always resets admin's password based on the value specified in userinitcfg.yaml if the password meets the requirement defined by password profile.

Can you share the tests with me / point me to the one you referring to?

The behavior you describe is what I expect, but in my tests it behaves different, that's why I created this issue :)

Let me try to explain the steps to reproduce the issue in more detail:

1/ NeuVector deployed via Helm, initial password `admin`.

2/ I create the Secret `neuvector-init` in namespace `neuvector` and define a custom password (fake one, not really in use, but same lenght and style), example content of `data.userinitcfg.yaml`:
```
always_reload: true
users:
- Fullname: admin
  Password: 1oABxxxX23Yxa4k5
  Role: admin
```

3/ I run `kubectl rollout restart deployment -n neuvector neuvector-controller-pod`

4/ Aftwards login is possible with the new password as defined in `neuvector-init`.

5/ Now I change the Secret `neuvector-init` a second time and set a different password for user `admin` in `data.userinitcfg.yaml`.

6/ I perform again a deployment restart to force the controller to load the injected `/etc/config/userinitcfg.yaml` again.

7/ I verify that the mounted secret is updated and the injected password the new one by running `k exec -n neuvector neuvector-controller-pod-<podid> -it -- cat /etc/config/userinitcfg.yaml`

8/ I open the WebUI and login with user `admin` and the new password. The login fails with the new password, the old password is still working. I see `|ERRO|CTL|rest.updateAdminPass: already updated - Password of=admin` in the logs of the elected leader. There is no error related to an failed update because it doesn't match the requirements or something. The password update fails because of this if condition:  https://github.com/neuvector/neuvector/blob/main/controller/rest/configmap.go#L427

**Comment by kevinayres** [comment]
Can anyone respond to this ask, please?

**Comment by williamlin-suse** [comment]
I tried NV again and it works as expected following your steps.
Most likely your second new password is weak that NV doesn't allow it.
You can check the logs of NV controller pods.
There should be a log like "ERRO|CTL|rest.handleusercfg: Weak password - create=admin"
For password requirement, see page [Settings ] -> Users, API Keys & Roles -> Authentication and Security Policies

**Comment by wombelix** [comment]
> I tried NV again and it works as expected following your steps. Most likely your second new password is weak that NV doesn't allow it. You can check the logs of NV controller pods. There should be a log like "ERRO|CTL|rest.handleusercfg: Weak password - create=admin" For password requirement, see page [Settings ] -> Users, API Keys & Roles -> Authentication and Security Policies

I just changed one character, so the complexity was the same and there wasn't an Issue in the logs either.
I continue to hit the problem but if you can't reproduce it, then it doesn't make much sense to spend more time.
