### ISSUE TITLE
学习模式下，Enforcer会增加网络延迟，出现服务响应时长大于500ms的情况

### ISSUE THREAD

**Issue by youzhiye** [neuvector/neuvector#141]
**Environment**
Platform: Kubernetes
Kubernetes/Platform Version(s): 1.16
**Describe the bug**
使用http_load测试enforcer对延迟的影响，跟无enforcer的状态下对比（多次），发现均存在最大响应时间大于500ms的情况。

<img width="945" alt="image" src="https://user-images.githubusercontent.com/17666805/159898361-534dca85-16bd-40de-877b-eb5e33e66302.png">

**Comment by becitsthere** [comment]
In the learning mode, neuvector is never sniffing the traffic, so it won't affect the throughput, unless the CPU on the testing server are fully loaded, then the enforcer will compete the CPU with the testing program.

**Comment by Akityo** [comment]
@becitsthere  but if in the learning mode , network rules don't work , pod A learning mode ,Pod B protect mode , rule: pod A to Pod B  DENY，rule don't work， if you try to protect Pod A to prevent other Pod access ，you need to let they all in protect mode  :(  which is affect the throughput

**Comment by youzhiye** [comment]
@becitsthere In the learning mode, I use 48C128G server for test. The results still affect the throughput（no performance limits）。
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/17666805/163095702-92caab21-1452-4e5b-b241-f1747d20a516.png">
CPU performance is sufficient to use for enforcer
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/17666805/163096448-fd74d615-f694-4095-9276-ed49aa6e3582.png">
<img width="777" alt="image" src="https://user-images.githubusercontent.com/17666805/163097903-51b9c5b9-abef-4329-818f-41a65f47f93e.png">
