### ISSUE TITLE
Neuvector Multiple Cluster Join Cluster

### ISSUE THREAD

**Issue by tsaomichael** [neuvector/neuvector#1417]
**Environment**
EKS v1.27.5, neuvector app version: 5.3.2

**Describe the bug**
Install two Kubernetes clusters, A and B, using Helm. Setting cluster A as the primary cluster is fine, but when trying to join cluster B to the primary cluster using the provided token, it fails with the error "Failed to join primary cluster: EOF."

**To Reproduce**
1. Multiple Cluster 
2. Join Cluster
3. Input primary cluster token, controller server/port and The Currect Cluster Name

**Expected behavior**
Failed to join primary cluster: EOF.

**Comment by williamlin-suse** [comment]
Please enable controller control path debug (Settings -> Configuration) , reproduce the issue & collect debug logs from all controller pods on both clusters.

**Comment by tsaomichael** [comment]
When I turn on the controller, the following error appears。

2024-06-20T13:36:33.44 |ERRO|CTL|rest.sendRestReqInternal: Failed to make request - err=Post "https://neuvector.testlab.com:443/v1/fed/join_internal": EOF proxyOption=0 timeout=10s url=https://neuvector.testlab.com:443/v1/fed/join_internal
2024-06-20T13:36:33.44 |DEBU|CTL|rest.writer.WriteHeader: 500 - Method=POST URL=https://neuvector-svc-controller.neuvector:10443/v1/fed/join

**Comment by williamlin-suse** [comment]
What about the debug logs on the primary cluster when the downstream cluster fails to join it?

**Comment by tsaomichael** [comment]
I’ve found the cause of the issue: the firewall settings for the managed service connecting to the master were not configured correctly. Thanks
