### ISSUE TITLE
network rule collection

### ISSUE THREAD

**Issue by brness** [neuvector/neuvector#145]
i just read the source code of agent, and the logic of network control was related with DP, according to the dp package, the network policy was written into the dp_policy_handler, but the **monitoring logic seems lost**, cause there should be a local loop detection of the network traffic , when a new traffic comes in and out, the monitor progaram should match the traffic with the dp_policy_handler, and if not match, it should return a deny action. So can someone elaborate it for me, and it do confuse me a lot?
Here is the logic graph i draw from the code:
![image](https://user-images.githubusercontent.com/22000324/160363217-03459093-fef7-4c3e-aafb-684cc47ffcd1.png)

**Comment by longpi1** [comment]
You don't understand

**Comment by brness** [comment]
> You don't understand

**Comment by becitsthere** [comment]
In monitor mode, dp is not inline to the traffic. It is like a sniffer, so it doesn't make allow/deny desicions.

**Comment by brness** [comment]
@becitsthere so my logic was partially right? and thanks for confirming my thought and one last question, Where is the logic of traffic loop detection? i couldn't find it in the dp code...

**Comment by smallcoderhujin** [comment]
@brness traffic loop detection code path: dp/pkt.c dp_data_thr -- dp_rx  -- dp_rx_v1

I'm also looking at the source code of dp, and I've encountered a problem. When dp process packets,  calculate the policy/session action, but I don't know where to specifically apply this action.

I found that the nfq-type port will call netfilter to process the calculated action, the source code  path: dp/nfq.c:66
