### ISSUE TITLE
RBAC error preview 3

### ISSUE THREAD

**Issue by zoopster** [neuvector/neuvector#151]
**Environment**
Platform: AWS EC2
Kubernetes/Platform Version(s): k3s 1.23.4

**Describe the bug**
Kubernetes clusterrole "neuvector-binding-nvdlpsecurityrules" is required to grant delete,list permission(s) on nvdlpsecurityrules resource(s).

Cannot find Kubernetes clusterrolebinding "neuvector-binding-nvdlpsecurityrules"(kubernetes api: Failure 404 clusterrolebindings.rbac.authorization.k8s.io "neuvector-binding-nvdlpsecurityrules" not found).

**To Reproduce**
1. Install via helm
2. login

**Expected behavior**
No errors appear

**Workaround** (provided by FM)
Resolved by applying the dlp CRD YAML
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/dlp-crd-k8s-1.19.yaml 

Create the ClusterRole: 
kubectl create clusterrole neuvector-binding-nvdlpsecurityrules --verb=list,delete --resource=nvdlpsecurityrulesand 
Creating the ClusterRoleBinding with: 
kubectl create clusterrolebinding neuvector-binding-nvdlpsecurityrules --clusterrole=neuvector-binding-nvdlpsecurityrules --serviceaccount=neuvector-system:default

**Comment by hwaastad** [comment]
I think this is resolved in b1.
If installing crd and core charts separate, make sure serviceaccount is the same in both.

**Comment by bgoareguer** [comment]
I confirm this is resolved in b1.

**Comment by zoopster** [comment]
confirmed using helm chart version v2.2.0-b1!! Thank you.
