### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by zoopster** [neuvector/neuvector#152]
Under policy/admission controls CONFIGURATION is spelled wrong - CONFIGUATION (missing the r). The modal that pops up has the same misspelling.
<img width="1229" alt="Screen Shot 2022-03-30 at 15 28 16" src="https://user-images.githubusercontent.com/1301708/160915820-f1d269e1-1478-44cc-90bf-d9d1140014fe.png">

**Comment by xingzhang-suse** [comment]
The misspelling issue has been changed.
![Screen Shot 2022-03-30 at 2 47 56 PM](https://user-images.githubusercontent.com/96316881/160936774-331cfed5-dd9f-4abc-a56e-c72ab3add702.png)
![Screen Shot 2022-03-30 at 2 48 08 PM](https://user-images.githubusercontent.com/96316881/160936779-d248d2e9-8ce3-41b4-977d-f1edf0c9859a.png)
