### ISSUE TITLE
Possibility to reduce access rights from admin to reader for the api call v1/assess/admission/rule (HTTP POST)

### ISSUE THREAD

**Issue by NickOosterhuis** [neuvector/neuvector#1703]
### Summary
I would like to request a change to the access control for the HTTP POST call to the `/v1/assess/admission/rule` endpoint, allowing it to be accessible with `reader` permissions rather than requiring admin rights.

### Problem Description
Currently, the` /v1/assess/admission/rule` API endpoint requires admin permissions to function. This poses a security concern when implementing CI/CD pipelines to verify if an image conforms to the set admission rules. For these pipelines, adding an API key with admin rights increases the risk of unintended changes to platform configurations, as the key has access to a broad range of API calls.

### Proposed Solution
Allow the `/v1/assess/admission/rule` endpoint to accept API calls from a reader role instead of requiring admin permissions. This adjustment would enable CI/CD pipelines to perform image validation without risking unnecessary exposure of high-privilege credentials.

### Use Case
In a typical CI/CD pipeline, the goal is to verify whether an image meets the platform's admission rules. With reduced permissions:
- It becomes safer to distribute API keys to multiple pipelines.
- There is less risk of misusing API keys since they would be restricted to read-only operations rather than administrative actions.

### Benefits
- Improved Security: Reduces the exposure of high-privilege API keys in CI/CD environments.
- Enhanced Usability: Makes it easier to integrate admission rule checks into pipelines without needing excessive permissions.
- Minimized Risk: Prevents accidental or unauthorized changes to platform configurations.

Thank you for considering this feature request! Please let me know if further clarification or details are needed.

**Comment by williamlin-suse** [comment]
The following steps should work for your needs
1. UI -> Settings -> Users, API Keys & Roles -> Roles. Create a custom role with Admission Control view/modify and other permissions you need.
2. UI -> Settings -> API Keys. Create an api key with the global role as the role created in step1
3. Use the api key created in step 2 in CI/CD

**Comment by NickOosterhuis** [comment]
> The following steps should work for your needs
> 
> 1. UI -> Settings -> Users, API Keys & Roles -> Roles. Create a custom role with Admission Control view/modify and other permissions you need.
> 2. UI -> Settings -> API Keys. Create an api key with the global role as the role created in step1
> 3. Use the api key created in step 2 in CI/CD

Ah thank you! I didn't think of this before. This works great. :)
