### ISSUE TITLE
WAF Sensors can not match the rule

### ISSUE THREAD

**Issue by freeit-gyh** [neuvector/neuvector#171]
**Environment**
Platform: K8s
Kubernetes/Platform Version(s): v1.19.1
Neuvector Version: preview-3

**Describe the bug**
I'm not sure if this is a bug,maybe it is my configuration issue；
I have configure rgxp to waf sensors,like this:
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/42790582/162234867-be84c67c-4073-4e4c-bdc1-38e15b58b7b4.png">
we can see that "and 1=1" can matched rgxp .

Then i add this policy to dvwa group:
<img width="1736" alt="image" src="https://user-images.githubusercontent.com/42790582/162235512-fd71a494-e501-4fa7-92cd-c0549c77efb8.png">

Then i access dvwa and test it,but the payload can not match the waf rule.
<img width="895" alt="image" src="https://user-images.githubusercontent.com/42790582/162236173-eb5303e9-dd41-44bb-a1ae-bab3312587ab.png">
I want to know why,who can tell me the reason or principle，there are many rgxp that come from imperva signature can not match the waf sensors rule.
The rgxp come from imperva waf signature,imperva waf can matched it.

Thanks!

**Comment by gfsuse** [comment]
Your regex pattern looks good, please go to network activity page and right click the group you are testing and select packet capture, then you can submit the form(sql injection), then stop and save capture. Please attach your pcap file here. Thanks

**Comment by freeit-gyh** [comment]
[01119c16cf2b4b2409a90a99e2c9f2fbc3f0aba82aa097235cddfb50f3ac87bbcb32c869.pcap.zip](https://github.com/neuvector/neuvector/files/8631662/01119c16cf2b4b2409a90a99e2c9f2fbc3f0aba82aa097235cddfb50f3ac87bbcb32c869.pcap.zip)

Hi 
I upload the capture packet,pls help check

- source ip : 172.18.205.126
- dest ip: 192.168.2.162
you can filter out the 127.0.0.1
i tigger the traffic by "and 1=1" ,there is no any custome waf rule  log

**Comment by gfsuse** [comment]
Hi
As I expected, the url request is url encoded and also there are other characte in the url request. I provided a solution regex in attached picture. 
Regards,
<img width="1872" alt="githubissue171" src="https://user-images.githubusercontent.com/95308753/166982362-6c85c1c4-ef00-44e4-b969-e26fc13f5c80.png">
<img width="988" alt="githubissue171_solution" src="https://user-images.githubusercontent.com/95308753/166982387-3d8baf6f-058f-46f8-8b20-80a5ac40c786.png">
