### ISSUE TITLE
Build cross-platform

### ISSUE THREAD

**Issue by loofah-98** [neuvector/neuvector#199]
If I want to run NeuVector on ARM64 platform, how do I build the various components of NeuVector

**Comment by garyduan** [comment]
Currently, ARM platform is not supported, especially because of the endianness issue in the network packets handling.

**Comment by spr-mweber3** [comment]
@garyduan Did you already collect enough user feedback that suggests a higher demand for arm64 images than before? We'd like to deploy Neuvector to nodes of an EKS cluster which are running on arm64 architecture.
