### ISSUE TITLE
[Neuvector] Clicking on EULA do not accept button does not return anything and stays in the same page

### ISSUE THREAD

**Issue by anupama2501** [neuvector/neuvector#218]
**Environment**
Platform: [e.g. Kubernetes, OpenShift, Rancher, Managed k8s (AKS, EKS, GKE, IKS, ...), ...] Rancher 
Kubernetes/Platform Version(s): v1.22.9

**Describe the bug**
After installing neuvector partner chart and launching the neuvector UI, navigates us to the End User License Agreement page. On this page, if we click on do not accept button nothing happens on the screen and we stay in the same page. If we click the do not accept button the UI is refreshed and we are still on the same page.

**To Reproduce**
1. Create a any cluster - I tried with RKE1 node driver 3 worker, 1 etcd, 1 cp
2. Install neuvector app from explorer >> apps >> Rancher charts
3. From left navigation, launch neuvector UI
4. In the EULA click on do not accept

**Result**
Nothing happens on the page and we stay on the same page.

**Expected Result**
Additional details should be provided quoted from neuvector product page:
```
YOUR USE OF THE SOFTWARE IS EXPRESSLY CONDITIONED ON YOUR ACCEPTANCE OF THE TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE TO ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT, YOU MAY NOT INSTALL OR USE THE SOFTWARE.
```

**Comment by garyduan** [comment]
This will be fixed in 5.0 release.
