### ISSUE TITLE
multiple container runtime at the same time

### ISSUE THREAD

**Issue by Hsince** [neuvector/neuvector#235]
We will deploy different container runtime implementations at the same time.
It doesn't seem to be supported currently.

I would like to be able to support connecting multiple container runtimes at the same time.

**Comment by jayhuang-suse** [comment]
Multiple container runtime environments on a single node imply the complexity of the management. It could cause performance degradation.

Neuvector will dedicate one container runtime to simplify and enhance the performance of any k8s/rancher cluster under a production environment. No plan to support multiple container runtimes so far. Thanks.
