### ISSUE TITLE
Gow to build development and debugging environment for neuvector?

### ISSUE THREAD

**Issue by haolipeng** [neuvector/neuvector#244]
I want to build a development and debugging environment for neuvector,
It is best to be able to perform GDB single-step debugging on the neuvector/agent code

What is the development environment for neuvector developers?

Is GDB used to debug the process in the container?

current progress：
1、I have Deployed neuvector Using Kubernetes, and the manager, controller, enforcer, scanner and updater are running ok.
2、I successfully compile the agent and controller directory code

**Comment by garyduan** [comment]
GDB or halve are some tools that can be used to debug golang and C code.
