### ISSUE TITLE
Hard-coded location for components

### ISSUE THREAD

**Issue by aplanas** [neuvector/neuvector#26]
In the code there is hard-coded the location of some binary utilities, mostly expected in `/usr/local/bin`.

**Comment by becitsthere** [comment]
Duplicate to #24

**Comment by becitsthere** [comment]
Duplicate of #24

**Comment by garyduan** [comment]
Ok. I will close this issue and use #24 to track it.

**Comment by aplanas** [comment]
No, is not duplicated.

As commented, in the code (for example https://github.com/neuvector/neuvector/blob/main/monitor/monitor.c#L102) there are locations in the file system that are hardcoded, pointing in `/usr/local/bin`.  This can be a problem when, lets say, we want to build a package for it (rpm, deb, or for other distributions)
