### ISSUE TITLE
How to achieve the effect of default blocking container network packet

### ISSUE THREAD

**Issue by longpi1** [neuvector/neuvector#283]
When I used Neuvector recently, I found that when the container was switched to protected mode, enforcer would create the corresponding Veth pair and some TC rules for the container, and then I found that it was possible to block the network packets of the container. How did that happen? Is it because of TC rule?
Looking forward to your reply, thank you very much!

**Comment by brness** [comment]
take a look at Vswitch

**Comment by longpi1** [comment]
> take a look at Vswitch

？？？？

**Comment by garyduan** [comment]
The enforcer will consume the packets, forward the allowed packets and the bad ones are dropped.

**Comment by longpi1** [comment]
> The enforcer will consume the packets, forward the allowed packets and the bad ones are dropped.

I know that this part realizes packet dropping and packet releasing through packet Mmap based on vth-Neuv on DP side, but shouldn't packet Mmap technology only deal with cloned packets? What technique does enforcer use to block raw packets by default?

**Comment by Faker523** [comment]
@garyduan  where to find the tc rules ? enforcer pod ?
