### ISSUE TITLE
ProfileSetting in processEvent

### ISSUE THREAD

**Issue by brness** [neuvector/neuvector#284]
Recently, I just did some test in process control of Neuvector, and according to the source code, I known that this was implemented by fanotify. But what confuse me is the attribute of ProfileSetting, especially in the decision making progress of FAN_OPEN_PERM. Here is the code of processEvent.

```
if res != rule_denied && res != rule_allowed && profileSetting == share.ProfileShield { // not match any rule
	pass, ppe = fa.checkAllowedShieldProcess(id, path, pid, res)
	if pass {
		res = rule_allowed_image // image file only
		log.WithFields(log.Fields{"id": id, "ppe": ppe}).Debug("SHD: allowed")
	} else {
		res = rule_not_defined // reject it
	}
}
```

So my question is what's the point of profileSetting? and what's the differences between share.ProfileShield and share.Default?

**Comment by longpi1** [comment]
Can't read the code yourself?

**Comment by jayhuang-suse** [comment]
There are two baseline process profiles in neuvector's security policy. This variable makes the switch. For more details, please visit the online document. Thanks.

https://open-docs.neuvector.com/policy/processrules
