### ISSUE TITLE
File access rules for the host

### ISSUE THREAD

**Issue by oroch2022** [neuvector/neuvector#310]
There are no sensitive file read-write rules under the node group, but there are in the response rule name:host FileAccess. Violation
![EA298B78-288D-4dda-A9CC-48D1DD531D5C](https://user-images.githubusercontent.com/108665946/177136727-2fca7a33-f1a8-4f3e-b209-19df43b9cc70.png)

**Comment by garyduan** [comment]
Sensitive files are automatically monitored. There is a list in the file access config dialog of what sensitive files/folders are.
