### ISSUE TITLE
A few bugs that we can't track

### ISSUE THREAD

**Issue by gk-j2** [neuvector/neuvector#313]
**Environment**
Platform: Kubernetes
Kubernetes/Platform Version(s):  1.20.12
10 clusters in Federation Management
Average 300 pods per cluster

**Describe the bug**
1) Authentication fails for no reason.

2) Further after this problem, the controller becomes unavailable.

3) In a multicluster infrastructure, after the controller becomes unavailable, we redeploy it and receive information in the main console that the cluster is disabled, although the redeployed cluster says that it is included in the multicluster architecture.

4) In general, for inexplicable reasons, clusters are turned off. When trying to synchronize with the cluster, sometimes a license error occurs and the console freezes.

**To Reproduce**
We cant get steps for reproduce because we dont have a lot of time to check all logs and more this problems.

**Expected behavior**
We cannot provide steps to repeat because we do not have an understanding at what point the problems appear, and constantly monitoring their status is not very convenient. Using prometheus-exporter does not provide information that it is not possible to authenticate or that the managed cluster is down and cannot be synchronized.

**Screenshots**

![1](https://user-images.githubusercontent.com/55018447/177503518-304c8d27-529b-4526-a9e6-c547ecb110d2.png)
![2](https://user-images.githubusercontent.com/55018447/177503531-a22401d2-7b73-4086-bac4-c2ed9ebfe722.png)
![3](https://user-images.githubusercontent.com/55018447/177503536-c4ef546a-30f6-444d-a533-63c8f088797a.png)
![4](https://user-images.githubusercontent.com/55018447/177503541-9e42c9e8-e3db-482e-a667-b6aae852f2ac.png)
![5](https://user-images.githubusercontent.com/55018447/177503547-93617848-3b63-4b0e-aa9e-4eab3cdd5482.png)

**Logs**
[controller-pod1-ControllerUnavailible.txt](https://github.com/neuvector/neuvector/files/9052975/controller-pod1-ControllerUnavailible.txt)
[controller-pod1-NonLogin.log](https://github.com/neuvector/neuvector/files/9052977/controller-pod1-NonLogin.log)
[controller-pod2-ContollerUnavialible.txt](https://github.com/neuvector/neuvector/files/9052978/controller-pod2-ContollerUnavialible.txt)
[controller-pod3-ControllerUnavailible.txt](https://github.com/neuvector/neuvector/files/9052979/controller-pod3-ControllerUnavailible.txt)
[manager-pod-NonLogin.log](https://github.com/neuvector/neuvector/files/9052980/manager-pod-NonLogin.log)

**UI Issue**
Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome 100
 - Version 5.0.0 Release
 - For each container  4 cpu and 4Gi

**Additional context**

**Comment by garyduan** [comment]
Looks like a deployment error. Please attach the deployment yaml file or helm chart settings.

**Comment by gk-j2** [comment]
[controller.conf.yaml.txt](https://github.com/neuvector/neuvector/files/9205952/controller.conf.yaml.txt)
Hello! I am attaching the configuration yaml of the controller. It was deployed via helm. What exactly needs to be pinned from Helm chart? We used the standard chart.

**Comment by becitsthere** [comment]
We have identified a potential issue that can be related to what you have seen. The fix will be included in 5.0.3.
