### ISSUE TITLE
[Query]Reset Neuvector Policy

### ISSUE THREAD

**Issue by brness** [neuvector/neuvector#316]
**Is your feature request related to a problem? Please describe.**
If there is a way to reset the Neuvector policy?
In my situation, the staging enviroment will do all the unitest or integrate test, and it's for learning phase. but how can i reuse the staging enviroment neuvector, so when staging pipeline was triggered I can use the same Neuvector but everything was reset.

**Describe the solution you'd like**
a api that i can reset the whole Neuvector

**Describe alternatives you've considered**
build up a Neuvector each time a MR was committed to main branch. Or clear the policy in consul

**Additional context**
or do i miss undertand the automation of neuvector, I'm quite confused?
@jeffhuang4704 @garyduan

**Comment by gtam** [comment]
If I understand your use case correctly, you can implement ConfigMap for initial configurations and don't set up persistent storage.  Each time you are done with the staging environment, scale the controllers to zero.; then scale the controllers back to 3 replicas.  This will wipe out everything and initialize with ConfigMap configurations.

**Comment by brness** [comment]
> If I understand your use case correctly, you can implement ConfigMap for initial configurations and don't set up persistent storage. Each time you are done with the staging environment, scale the controllers to zero.; then scale the controllers back to 3 replicas. This will wipe out everything and initialize with ConfigMap configurations.

Yes, That's just what i mean. We did have the persistent storage in the production phase in case of restart of controller. Thanks a lot!! @gtam
