### ISSUE TITLE
docker build not possible 

### ISSUE THREAD

**Issue by haarchri** [neuvector/neuvector#32]
docker build is not possible - in code we see a lot of internal ips like `10.1.127.12:5000` 

https://github.com/neuvector/neuvector/search?q=10.1.127.12
https://github.com/neuvector/neuvector/blob/main/Makefile#L3_L4
https://github.com/neuvector/neuvector/blob/main/build/Dockerfile.all#L2
https://github.com/neuvector/neuvector/blob/main/build/Dockerfile.controller#L2
https://github.com/neuvector/neuvector/blob/main/build/Dockerfile.ctrlenf#L1

**Comment by garyduan** [comment]
Self build is not supported yet and will be supported in the future. Using #24 to follow up the issue.

**Comment by garyduan** [comment]
Duplicate of #24
