### ISSUE TITLE
[Query] Difference between Basic and Zero drift protection

### ISSUE THREAD

**Issue by DilanUA** [neuvector/neuvector#322]
## Description
I have been testing the functionality of neuvector recent 5.0 release and came across this question on $subject.
I have realized that zero drift basically do some machine learning on the image itself and come up with process, file and network rules.

What I don't get is this other mode called "Basic". Is it the "Behavioral learning protection" that is explained in this doc - https://open-docs.neuvector.com/policy/processrules#behavioral-learning-based-process-protection or something different and how would that be different from "zero drift" mode?

@jayhuang-suse @becitsthere Any clue on this is helpful. Thanks.

**Comment by jayhuang-suse** [comment]
Thanks for your interest. The "Basic" baseline process profile is simply a "white-list" rule-based profile. Users need to provide the allowed processes or learn the processes during Discover profile mode. We used to have the "Basic" baseline profile for all pre-5.0 versions. The "Zero-Drift" baseline process profile is an add-on feature on top of the "Basic" profile to provide a better-secured way to protect the containers.

**Comment by DilanUA** [comment]
> Thanks for your interest. The "Basic" baseline process profile is simply a "white-list" rule-based profile. Users need to provide the allowed processes or learn the processes during Discover profile mode. We used to have the "Basic" baseline profile for all pre-5.0 versions. The "Zero-Drift" baseline process profile is an add-on feature on top of the "Basic" profile to provide a better-secured way to protect the containers.

So, with basic profile, do we need to manually add rules? isn't there any machine learning involved?

**Comment by brness** [comment]
```Zero-drift process and file protection. This is the new default mode for process and file protections. Zero-drift automatically allows only processes which originate from the parent process that is in the original container image, and does not allow file updates or new files to be installed. When in Discover or Monitor mode, zero-drift will alert on any suspicious process or file activity. In Protect mode, it will block such activity. Zero-drift does not require processes to be learned or added to an allow-list. Disabling zero-drift for a group will cause the process and file rules listed for the group to take effect instead.```
this is the definition of zero-drift, and this seems not relavent to machine learing @DilanUA and it could be too heavy for each pod

**Comment by garyduan** [comment]
Not really machine learning. The document explains what they are, "only processes which originate from the parent process that is in the original container image".
