### ISSUE TITLE
[QUERY] Export All Configuration

### ISSUE THREAD

**Issue by brness** [neuvector/neuvector#326]
I try to build a CI/CD pipeline according to the Neuvector Wokflow, but during the step 16( export the production security policy), I find it's hard to export all policy just in one shell script. There are four type of resources, group, dlp, waf, admission, each of which containes a api which require a unique body construct.
So I check if there is a api contains all resource exportation, all I get is the 
![image](https://user-images.githubusercontent.com/22000324/179474559-7b94d823-a535-4b1b-b4c2-1add3f00becb.png)
and It's a data file, I cant' see what's inside.

Here is my question: What's the usage of the api in the pic? And Is there a api can export all neuvector resource yaml file and don't need to require specific name of each resource? or default to export all configuration?
@garyduan @jeffhuang4704

**Comment by garyduan** [comment]
It is a gzip file.

**Comment by brness** [comment]
> I try to build a CI/CD pipeline according to the Neuvector Wokflow, but during the step 16( export the production security policy), I find it's hard to export all policy just in one shell script. There are four type of resources, group, dlp, waf, admission, each of which containes a api which require a unique body construct.

I download it with
```
root@ubuntu:~# curl -k -H "Content-Type: application/json" -H "X-Auth-Token: $_TOKEN_" "https://$_controllerIP_:31908/v1/file/config" --output NV20060.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19784    0 19784    0     0  90337      0 --:--:-- --:--:-- --:--:-- 90337
root@ubuntu:~# file NV20060.gz
NV20060.gz: data
root@ubuntu:~# gunzip NV20060.gz

gzip: NV20060.gz: not in gzip format
```
and it shows it's a data file ,I can't decompress it with gzip. So what might be the problem?
