### ISSUE TITLE
Settings in ldapinitcfg.yaml do not work on new deployment

### ISSUE THREAD

**Issue by zOrg1331** [neuvector/neuvector#340]
**Environment**
Platform: Rancher
Kubernetes/Platform Version(s):  v1.21.12

**Describe the bug**
On initial NeuVector deployment (in our case via fleet and Rancher), LDAP settings provided via ConfigMap as "ldapinitcfg.yaml" are not considered.
The following error can be observed in "controller" logs:
```
2022-07-28T10:56:38.205|ERRO|CTL|rest.handleldapcfg: Invalid default role - server=ldap1
2022-07-28T10:56:38.205|ERRO|CTL|rest.LoadInitCfg:     ldap init configmap failed: Invalid default role 
```

**To Reproduce**
1. Prepare LDAP configuration via ConfigMap, i.e.:
```
      ldapinitcfg.yaml: |
        always_reload: true
        directory: OpenLDAP
        Hostname: iam.test.com
        Port: 636
        SSL: false
        base_dn: ou=people,dc=test,dc=com
        #bind_dn:
        #bind_password:
        group_member_attr: memberUid
        username_attr: uid
        Enable: false
        Default_Role: none
```

3. Start new deployment or delete all "controller" pods to initiate their re-deployment.
4. Go to NeuVector settings.
5. Observe empty LDAP settings.
6. The aforementioned error will appear in "controller" logs.

**Expected behavior**
The provided LDAP settings as ldapinitcfg.yaml via ConfigMap are taken into account by NeuVector.

**Screenshots**
N/A

**UI Issue**
N/A

**Additional context**
There is a workaround to create a "server" instance via CLI at first.

**Comment by williamlin-suse** [comment]
Your configmap configuration is incorrect. 
To specify None for LDAP default user, please use 
Default_Role: ""

**Comment by zOrg1331** [comment]
> Your configmap configuration is incorrect. To specify None for LDAP default user, please use Default_Role: ""

Indeed, thank you! This resolved the problem. Quite unexpected outcome.
