### ISSUE TITLE
[UI] Magic string password is in plain text

### ISSUE THREAD

**Issue by jaimeyu** [neuvector/neuvector#367]
Sorry, not sure the context or risk but I found a plaintext password but I haven't found the place where we can set it/tune it. 
```
 auth_status=$(
    curl --insecure --write-out '%{http_code}' \
    -s -o ${outputDir}/auth_response \
    --location --request POST "${base_url}/auth" \
    --header 'Content-Type: application/json' \
    --data-raw '{"username":"u-admin","password":"1qazXSW@"}'
  )
```
on line 
https://github.com/neuvector/manager/blob/main/admin/test/REST_API/test_shell.sh#L28

**Comment by williamlin-suse** [comment]
it's for testing only
