### ISSUE TITLE
Issue trying to connect Multi-Clusters

### ISSUE THREAD

**Issue by danieljpowley** [neuvector/neuvector#387]
When trying to link up multi-clusters I always get timed out, there's not much to go by in the way of logs but I can see a couple of errors in the ingress pods: -

 2022-08-24T15:03:09.495|ERRO|CTL|rest.sendReqToMasterCluster: Request failed - proxy={proxyUsed:false enabled:false url:} status=400 Bad Request timeout=50s url=https://neuvector.xxxxx.xxxxxx.net:443/v1/fed/join_internal

And

2022-08-24T15:03:09.495|ERRO|CTL|rest.handlerJoinFed: - data=Request is missing required HTTP header 'Token' localPort=443 localServer=neuvector.xxxxx.xxxxxx.net proxyUsed=false statusCode=400

It looks like the token isn't being sent, if I run a test via postman I can see that it goes through just fine. I get the same issue on 2.2.0/2.2.1/2.2.2

I'm running this in Azure/AKS/k8s version: v1.21.9  -  Any ideas?

Thanks and best regards, Dan

**Comment by williamlin-suse** [comment]
What do you mean by "I get the same issue on 2.2.0/2.2.1/2.2.2" ? Are you using Neuvector 2.2.0/2.2.1/2.2.2 ?
It looks like your 2nd cluster cannot reach the primary cluster's neuvector-service-controller-fed service.
Please make sure your configuration(ip/port) is correct.

**Comment by danieljpowley** [comment]
I am running 2.2.2 at the moment, I meant I've tried on the previous versions and had the same issue. 

It's using ClusterIP, it looks like the default ports are being added to internal IP's - neuvector-svc-controller doesn't have an IP.

One's set up with the Fed Master and the other is set up with Fed Managed.  

Yes, it is being operated through the UI.

I've tried multiple variations when promoting one and adding one - from hostnames/external IP with default ports and 443 the result has always been the same.

I have been promoting the cluster with the Fed Master services and the slave has always been the cluster I'm trying to join.

**Comment by williamlin-suse** [comment]
Please provide the info:
1. The output of "kubectl get svc -n neuvector -o wide" & "kubectl get pod -n neuvector -o wide" from both the primary cluster & the 2nd cluster.
2. What ip/port do u use for joining? (on UI there are 2nd cluster's ip/port & primary cluster's ip/port for joining fed)
Does your primary cluster has neuvector-service-controller-fed service?

**Comment by danieljpowley** [comment]
1. Fed Master: -
![image](https://user-images.githubusercontent.com/20566753/187405008-267131a4-8361-4e72-9f40-fa27f3083d64.png)

Fed Managed: -
![image](https://user-images.githubusercontent.com/20566753/187405237-d8529657-ba0b-4163-9b9f-2855026fe82d.png)

2. The Master Cluster - For the master - I have tried the load balancer ip/11443 and the load balancer ip/10443, which didn't work.

Also, load balancer ip/443 and load balancer/443 - which didn't work.

Also, HostName/11443 and HostName/10443 - which didn't work.

Also, HostName/443 and HostName/443 - which didn't work.

Each time I have demoted the master and added the ports above when promoted it

**Comment by williamlin-suse** [comment]
All of your services' type is ClusterIP.
Which service is accessible from outside the cluster?

On master cluster, neuvector-svc-controller-fed-master service must be accessible from all the managed clusters.
When you promote the master cluster, do you provide hostname or ip ?
If you expose neuvector-svc-controller-fed-master service by master-HostName/11443, master-HostName must be resolvable on the managed clusters. You could use curl command on the managed clusters to see whether https://{master_HostName}:11443 is reachable.

On managed clusters, neuvector-svc-controller-fed-managed service must be accessible from the master cluster.
If you expose neuvector-svc-controller-fed-managed service by managed-HostName/10443, managed-HostName must be resolvable on the master cluster. You could use curl command on the "master cluster" to see whether https://{managed_HostName}:10443 is reachable.

In your first comment, there is a debug log:
2022-08-24T15:03:09.495|ERRO|CTL|rest.sendReqToMasterCluster: Request failed - proxy={proxyUsed:false enabled:false url:} status=400 Bad Request timeout=50s url=[https://neuvector.xxxxx.xxxxxx.net:443/v1/fed/join_internal](https://neuvector.xxxxx.xxxxxx.net/v1/fed/join_internal)
It means the managed cluster tried to connect to master cluster by https://neuvector.xxxxx.xxxxxx.net:443
Which service on master cluster exposes fed master server by port 443 ?
Did you get the joining token thru master cluster's UI?

**Comment by danieljpowley** [comment]
All the services go through 443: -

This is the slave: -
![image](https://user-images.githubusercontent.com/20566753/187445543-91ad3965-7818-4774-97b8-06b336e21e87.png)

This is the Master: -
![image](https://user-images.githubusercontent.com/20566753/187445884-f51c0c5b-84a0-45c7-b18e-8e42712d4045.png)

The Master has the fed master services and the slave has the fed managed services installed. 

I get the joining token from the Master(Primary) and add it to the cluster that I was to join, I get this response if I go via hostnames: -

 
![image](https://user-images.githubusercontent.com/20566753/187446945-79db6a59-20ac-4aa2-9899-85fac83b9a63.png)

If I use the load balancers I get 400 Bad Request.

**Comment by williamlin-suse** [comment]
Are https://xxx/:10443 & https://xxx/:11443 valid URL in your curl commands?
Why don't you use https://xxx:10443 & https://xxx:11443 in your curl commands ?
Does ping work when you ping master cluster's hostname from managed cluster & ping managed cluster's hostname from master cluster ?
From your snapshot, I still don't see any LoadBalancer or NodePort service exposes neuvector server for access from out side the cluster.

**Comment by danieljpowley** [comment]
I got this sorted in the end, thank you for your help

**Comment by sumeet-zuora** [comment]
@danieljpowley we are also having same issue, can you please let us know what was the solution.

**Comment by reespozzi** [comment]
> All of your services' type is ClusterIP. Which service is accessible from outside the cluster?
> 
> On master cluster, neuvector-svc-controller-fed-master service must be accessible from all the managed clusters. When you promote the master cluster, do you provide hostname or ip ? If you expose neuvector-svc-controller-fed-master service by master-HostName/11443, master-HostName must be resolvable on the managed clusters. You could use curl command on the managed clusters to see whether https://{master_HostName}:11443 is reachable.
> 
> On managed clusters, neuvector-svc-controller-fed-managed service must be accessible from the master cluster. If you expose neuvector-svc-controller-fed-managed service by managed-HostName/10443, managed-HostName must be resolvable on the master cluster. You could use curl command on the "master cluster" to see whether https://{managed_HostName}:10443 is reachable.
> 
> In your first comment, there is a debug log: 2022-08-24T15:03:09.495|ERRO|CTL|rest.sendReqToMasterCluster: Request failed - proxy={proxyUsed:false enabled:false url:} status=400 Bad Request timeout=50s url=[https://neuvector.xxxxx.xxxxxx.net:443/v1/fed/join_internal](https://neuvector.xxxxx.xxxxxx.net/v1/fed/join_internal) It means the managed cluster tried to connect to master cluster by https://neuvector.xxxxx.xxxxxx.net:443 Which service on master cluster exposes fed master server by port 443 ? Did you get the joining token thru master cluster's UI?

@williamlin-suse Is this also the case when using an ingress controller and only exposing that as a LoadBalancer type for a cluster? 
For instance, I have the federated services up on the correct ports, but using Traefik to expose services externally, which listens on port 80. Is it possible at all with this setup to configure master and worker clusters, or is it necessary for each federated service to be of type LoadBalancer and externally open those ports too? 

Ideally I'm hoping a configuration for joining clusters could look like `ingress-host-name` as the entry point (attached to federated service and exposed via Traefik) on port 80


If it is possible, do the federated services need a separate ingress host name creating, different to that of the controller pod for webui? I see both services are annotated to reach the controller pod either way.
