### ISSUE TITLE
Unify tab names in Assets -> Nodes & Assets -> Containers

### ISSUE THREAD

**Issue by peteingithub** [neuvector/neuvector#399]
**Is your feature request related to a problem? Please describe.**
Assets -> Containers does only have icons, not written tab names. 

**Describe the solution you'd like**
Please add tab names in writing for Assets -> Containers. 

**Additional context**
Nodes vs Containers
![image](https://user-images.githubusercontent.com/86831399/187442595-c0db2745-aadc-43ec-bf0e-08afbbff37d6.png)

![image](https://user-images.githubusercontent.com/86831399/187442693-362e20af-0274-49ce-a6e1-d36921a1d4af.png)

**Comment by garyduan** [comment]
Make the window wider, the tab names will be shown, otherwise, hover over the icon, the text is shown.

**Comment by peteingithub** [comment]
Why not make the back end settings the same for both views? 
For me, in the same window width, one shows the names, the other does not.
Would it be possible to make the outcome the same?
