### ISSUE TITLE
Features for the US Federal Government

### ISSUE THREAD

**Issue by clemenko** [neuvector/neuvector#400]
Background. The US Federal Gov, specifically the DOD and the Intel community have certain requirements for applications on their networks. Here is a list of gaps that we need to fill to meet and potentially exceed the requirements. 

Requirements:

* Classification Banners - Good example - https://www.astrouxds.com/components/classification-markings/
* Logon Banners - Typically a modal that shows the required text : https://www.stigviewer.com/stig/aix_5.3/2014-10-03/finding/V-24331
* PKI Support - Must have the ability to support x509 client certificates for user authentication
* Air Gap instructions - How can the customer get the bits and use the bits on an air gapped network.

Extremely helpful:

* Move the CVE database from the image to a file. This allows for a MUCH easier path to getting the file across the air gap. Images take more time. Not to mention the size of the image vs a db file. 
* API documentation - With the customers integration Neuvector into their Enterprise Software Supply Chains they will need better documentation of the API.
* Technical enablement - Better guides on how to deploy.
    

cc: @bgulla

**Comment by garyduan** [comment]
Some of the requests have been converted to internal jira cases.

There is a advantage to package CVE database with the scanner in one image. For example, when we add a new source of vulnerability feed, the scanner is updated at the same time, otherwise, the user has to go through multiple steps to upgrade the scanning service.

Having said that, we will work with the users if they have specific requirements.

**Comment by clemenko** [comment]
For tracking purposes, can you list the Jira ticket numbers? 
The process for updating a database file is MUCH simpler than having to go to change control to update a container, especially on an air gapped network. Feel free to reach out over internal slack to chat about all this.

**Comment by clemenko** [comment]
#304

**Comment by clemenko** [comment]
Also Neuvector 5.0.4 does not support the CIS Profile 1.6 in RKE2.
