### ISSUE TITLE
Please reopen #337

### ISSUE THREAD

**Issue by zOrg1331** [neuvector/neuvector#409]
The issue #337 was closed by @garyduan with quite strange explanation, see: https://github.com/neuvector/neuvector/issues/337#issuecomment-1232252223_. Please, reopen the issue at least.
It is understandable if the project is not willing to implement the feature, but why closing the request then?

**Comment by garyduan** [comment]
I reopen 337 and close this one. The reason it was closed is, the attached code snippet doesn't exist in the code base.
