### ISSUE TITLE
[SCAN] False positives scanning alpine 3.14

### ISSUE THREAD

**Issue by mattfarina** [neuvector/neuvector#412]
**Environment**
scanner stand alone. Running in Rancher Desktop.

**Describe the bug**
When I scan alpine 3.14 it reports vulnerabilities that are not present in the image. False positives.

**To Reproduce**
1. run `docker pull alpine:3.14` to get the image locally
2. Scan the image by running `docker run --name neuvector.scanner --rm -e SCANNER_REPOSITORY=alpine -e SCANNER_TAG=3.14 -e SCANNER_ON_DEMAND=1 -v /var/run/docker.sock:/var/run/docker.sock -v /path/to/local/neuvector:/var/neuvector  neuvector/scanner`. Note, replace `/path/to/local/neuvector` with a local path that the volume can be attached to.
3. Open _scan_result.json_ and see the found vulnerabilities. They are openssl ones against 3.0.x before 3.0.3-r0. But, the openssl version in alpine is 1.1.1q-r0 which isn't part of the 3.x work. 1.1.1q is the latest on that major version. the CVEs don't list 1.x as being affected.

**Expected behavior**
No CVEs should be found

**Screenshots**
N/A

**UI Issue**
Desktop (please complete the following information):**
N/A

**Additional context**
You can find my scan results at https://gist.github.com/mattfarina/789921c340ddbcbfa18543792f50562d

**Comment by becitsthere** [comment]
https://github.com/neuvector/scanner/commit/ff785d797995ef1692e441ae11e6101f5d912947
