### ISSUE TITLE
Failed to get container 

### ISSUE THREAD

**Issue by d4b0zz** [neuvector/neuvector#42]
After using the helm chart provided in Rancher and modifying the following values to include the 5.0.0 preview versions, all controller (3) and enforcer (1) pods won't start:
kubectl get all -n neuvector
NAME                                            READY   STATUS             RESTARTS   AGE
pod/neuvector-controller-pod-8576986c7f-2hk5v   0/1     CrashLoopBackOff   3          86s
pod/neuvector-controller-pod-8576986c7f-mmgtg   0/1     CrashLoopBackOff   3          85s
pod/neuvector-controller-pod-8576986c7f-xj5bx   0/1     CrashLoopBackOff   3          85s
pod/neuvector-enforcer-pod-kbhzj                0/1     CrashLoopBackOff   3          78s
pod/neuvector-manager-pod-798c7bb866-bsjrk      1/1     Running            0          67m
pod/neuvector-scanner-pod-5b94c54657-9bvmw      1/1     Running            0          67m
pod/neuvector-scanner-pod-5b94c54657-frfxw      1/1     Running            0          67m
pod/neuvector-scanner-pod-5b94c54657-wbtmp      1/1     Running            0          67m

NAME                                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                         AGE
service/neuvector-service-webui           ClusterIP   10.43.165.209   <none>        8443/TCP                        67m
service/neuvector-svc-admission-webhook   ClusterIP   10.43.100.58    <none>        443/TCP                         67m
service/neuvector-svc-controller          ClusterIP   None            <none>        18300/TCP,18301/TCP,18301/UDP   67m

NAME                                    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/neuvector-enforcer-pod   1         1         0       1            0           <none>          67m

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/neuvector-controller-pod   0/3     3            0           67m
deployment.apps/neuvector-manager-pod      1/1     1            1           67m
deployment.apps/neuvector-scanner-pod      3/3     3            3           67m

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/neuvector-controller-pod-8576986c7f   3         3         0       67m
replicaset.apps/neuvector-manager-pod-798c7bb866      1         1         1       67m
replicaset.apps/neuvector-scanner-pod-5b94c54657      3         3         3       67m

NAME                                  SCHEDULE    SUSPEND   ACTIVE   LAST SCHEDULE   AGE
cronjob.batch/neuvector-updater-pod   0 0 * * *   False     0        <none>          67m

Here is what I get from the enforcer logs:
<html>
<body>

2022-01-27T03:26:39.009\|ERRO\|AGT\|container.(*containerdDriver).GetContainer: Failed to get container - error=container "751738dadbb7dc1e484dfbfed4fe9b9c222ca8c247b06d6bad51819bbc322c51" in namespace "k8s.io": not found
--
Thu, Jan 27 2022 4:26:39 am | 2022-01-27T03:26:39.009\|ERRO\|AGT\|main.main: Failed to get local device information - error=not found
Thu, Jan 27 2022 4:26:39 am | github.com/neuvector/neuvector/vendor/github.com/containerd/containerd/errdefs.init
Thu, Jan 27 2022 4:26:39 am | /go/src/github.com/neuvector/neuvector/vendor/github.com/containerd/containerd/errdefs/errors.go:41
Thu, Jan 27 2022 4:26:39 am | runtime.doInit
Thu, Jan 27 2022 4:26:39 am | /usr/local/go/src/runtime/proc.go:5480
Thu, Jan 27 2022 4:26:39 am | runtime.doInit
Thu, Jan 27 2022 4:26:39 am | /usr/local/go/src/runtime/proc.go:5475
Thu, Jan 27 2022 4:26:39 am | runtime.doInit
Thu, Jan 27 2022 4:26:39 am | /usr/local/go/src/runtime/proc.go:5475
Thu, Jan 27 2022 4:26:39 am | runtime.doInit
Thu, Jan 27 2022 4:26:39 am | /usr/local/go/src/runtime/proc.go:5475
Thu, Jan 27 2022 4:26:39 am | runtime.doInit
Thu, Jan 27 2022 4:26:39 am | /usr/local/go/src/runtime/proc.go:5475
Thu, Jan 27 2022 4:26:39 am | runtime.doInit
Thu, Jan 27 2022 4:26:39 am | /usr/local/go/src/runtime/proc.go:5475
Thu, Jan 27 2022 4:26:39 am | runtime.doInit
Thu, Jan 27 2022 4:26:39 am | /usr/local/go/src/runtime/proc.go:5475
Thu, Jan 27 2022 4:26:39 am | runtime.main
Thu, Jan 27 2022 4:26:39 am | /usr/local/go/src/runtime/proc.go:190
Thu, Jan 27 2022 4:26:39 am | runtime.goexit
Thu, Jan 27 2022 4:26:39 am | /usr/local/go/src/runtime/asm_amd64.s:1373
Thu, Jan 27 2022 4:26:39 am | container "751738dadbb7dc1e484dfbfed4fe9b9c222ca8c247b06d6bad51819bbc322c51" in namespace "k8s.io"
Thu, Jan 27 2022 4:26:39 am | github.com/neuvector/neuvector/vendor/github.com/containerd/containerd/errdefs.FromGRPC
Thu, Jan 27 2022 4:26:39 am | /go/src/github.com/neuvector/neuvector/vendor/github.com/containerd/containerd/errdefs/grpc.go:98
Thu, Jan 27 2022 4:26:39 am | github.com/neuvector/neuvector/vendor/github.com/containerd/containerd.(*remoteContainers).Get
Thu, Jan 27 2022 4:26:39 am | /go/src/github.com/neuvector/neuvector/vendor/github.com/containerd/containerd/containerstore.go:50
Thu, Jan 27 2022 4:26:39 am | github.com/neuvector/neuvector/vendor/github.com/containerd/containerd.(*Client).LoadContainer
Thu, Jan 27 2022 4:26:39 am | /go/src/github.com/neuvector/neuvector/vendor/github.com/containerd/containerd/client.go:248
Thu, Jan 27 2022 4:26:39 am | github.com/neuvector/neuvector/share/container.(*containerdDriver).GetContainer
Thu, Jan 27 2022 4:26:39 am | /go/src/github.com/neuvector/neuvector/share/container/containerd.go:294
Thu, Jan 27 2022 4:26:39 am | github.com/neuvector/neuvector/share/container.getDevice
Thu, Jan 27 2022 4:26:39 am | /go/src/github.com/neuvector/neuvector/share/container/common.go:191
Thu, Jan 27 2022 4:26:39 am | github.com/neuvector/neuvector/share/container.(*containerdDriver).GetDevice
Thu, Jan 27 2022 4:26:39 am | /go/src/github.com/neuvector/neuvector/share/container/containerd.go:121
Thu, Jan 27 2022 4:26:39 am | main.getLocalInfo
Thu, Jan 27 2022 4:26:39 am | /go/src/github.com/neuvector/neuvector/agent/agent.go:105
Thu, Jan 27 2022 4:26:39 am | main.main
Thu, Jan 27 2022 4:26:39 am | /go/src/github.com/neuvector/neuvector/agent/agent.go:361
Thu, Jan 27 2022 4:26:39 am | runtime.main
Thu, Jan 27 2022 4:26:39 am | /usr/local/go/src/runtime/proc.go:203
Thu, Jan 27 2022 4:26:39 am | runtime.goexit
Thu, Jan 27 2022 4:26:39 am | /usr/local/go/src/runtime/asm_amd64.s:1373
Thu, Jan 27 2022 4:26:39 am | 2022-01-27T03:26:39\|MON\|Process agent exit status 254, pid=1624724
Thu, Jan 27 2022 4:26:39 am | 2022-01-27T03:26:39\|MON\|Process agent exit with non-recoverable return code. Monitor Exit!!
Thu, Jan 27 2022 4:26:39 am | 2022-01-27T03:26:39\|MON\|Kill dp with signal 15, pid=1624723
Thu, Jan 27 2022 4:26:39 am | 2022-01-27T03:26:38\|DEBU\|dp0\|dp_data_thr: dp thread exits
Thu, Jan 27 2022 4:26:39 am | Leave the cluster
Thu, Jan 27 2022 4:26:39 am | Error leaving: Put http://127.0.0.1:8500/v1/agent/leave: dial tcp 127.0.0.1:8500: connect: connection refused
Thu, Jan 27 2022 4:26:39 am | 2022-01-27T03:26:39\|MON\|Clean up.

</body>
</html>

If I describe the container, the ID seems to add up:

kubectl describe pod/neuvector-enforcer-pod-kbhzj -n neuvector
...
Controlled By:  DaemonSet/neuvector-enforcer-pod
Containers:
  neuvector-enforcer-pod:
    Container ID:   containerd://751738dadbb7dc1e484dfbfed4fe9b9c222ca8c247b06d6bad51819bbc322c51
    Image:          docker.io/neuvector/enforcer.preview:5.0.0-preview.1
    Image ID:       docker.io/neuvector/enforcer.preview@sha256:3997f1323b6a5f49a57156388b5de0261a048d49d202402d954d49af2f1d4a30
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    254
      Started:      Thu, 27 Jan 2022 03:26:38 +0000
      Finished:     Thu, 27 Jan 2022 03:26:39 +0000
    Ready:          False
    Restart Count:  7
    Environment:
      CLUSTER_JOIN_ADDR:        neuvector-svc-controller.neuvector
      CLUSTER_ADVERTISED_ADDR:   (v1:status.podIP)
      CLUSTER_BIND_ADDR:         (v1:status.podIP)
    Mounts:
      /host/cgroup from cgroup-vol (ro)
      /host/proc from proc-vol (ro)
      /lib/modules from modules-vol (ro)
      /var/run/containerd/containerd.sock from runtime-sock (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-5f9ps (ro)
...

Given the error, it seems to look for the container in "k8s.io" namespace, which I don't have.

**Comment by jayhuang-suse** [comment]
Thanks for your feedback. 

Can I have your cluster/node information? Also, the modified HELM chart. Thanks.

**Comment by selvamt94** [comment]
Hi,

Can you please enable k3s container runtime and disable containerd runtime as below. k3s need to be enabled for RKE2 cluster. This option is not available in the rancher UI page, so you may need to edit values.yaml and add below configuration. We will include k3s runtime configuration in the container runtime configuration UI page in our next release. Thanks.

```
k3s:
  enabled: true
  runtimePath: /run/k3s/containerd/containerd.sock

containerd:
  enabled: false
  path: /var/run/containerd/containerd.sock

**Comment by d4b0zz** [comment]
That did the trick - thank you!
