### ISSUE TITLE
Admission control policy not applied

### ISSUE THREAD

**Issue by LucasVanHaaren** [neuvector/neuvector#434]
**Environment**
Platform: [Kubernetes, Managed k8s (GKE, DigitalOcean)]
Kubernetes/Platform Version(s): 1.22.13 (GKE), 1.23 (DigitalOcean), 1.24.0 (Kind)
Deployment: Helm Chart v2.2.3, Neuvector v5.0.3

**Describe the bug**
Enabling **Admission Control** feature and setting it to **Protect Mode** won't block non-compliant deployments and report them.
I created a Policy that deny to run as root in the namespace `rootless`.
Then when I try to run a simple busybox container (as root) in a pod in that namespace, nothing is blocked.

**To Reproduce**
1. Deploy v2.2.3 Helm chart

```bash
helm upgrade --install neuvector neuvector/core --version 2.2.3 \
--set registry=docker.io \
--set containerd.enabled=true \
--create-namespace \
--namespace neuvector
```

2. Enable **Admission Control** and set to **Protect Mode**
![image](https://user-images.githubusercontent.com/29121316/191926143-9585bbee-10bb-45f0-bb00-cc0fab7e4397.png)

3. Create a policy that deny running as root in the `rootless` namespace
![image](https://user-images.githubusercontent.com/29121316/191930407-05842a62-80cd-4558-a0b9-4367e8ddacaf.png)

4. Run as root and see nothing is blocked and reported
```bash
kubectl run root-test --rm -it --image busybox -n rootless -- sh

/ # id
uid=0(root) gid=0(root) groups=10(wheel)
```
![image](https://user-images.githubusercontent.com/29121316/191928117-e4e2766e-b2c5-46de-ba26-5fcf0bf6b5a1.png)

**Expected behavior**
Policy created should be applied and prevent any pod to run as root in the `rootless` namespace because of Admission control activated and set to protect mode

Feel free to ask for any details I have missed in explanation,
Thanks in advance for your help :heart:

**Comment by williamlin-suse** [comment]
Please click Policy -> Admission Control -> More operations -> Advanced setting -> Test & see whether the admission control test is good.
What's the output of "kubectl get svc -n neuvector -o wide"?

**Comment by LucasVanHaaren** [comment]
Hi, thank you for your reply !

I confirm admission control connection test passed (using cluster service) :
![image](https://user-images.githubusercontent.com/29121316/191955665-ab48f861-498d-4653-bbed-b2ee4c8bf86f.png)
 
And here is the output of the command above : 
```bash
NAME                              TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                         AGE    SELECTOR
neuvector-service-webui           NodePort    10.96.190.13   <none>        8443:32060/TCP                  4h6m   app=neuvector-manager-pod
neuvector-svc-admission-webhook   ClusterIP   10.96.99.11    <none>        443/TCP                         4h6m   app=neuvector-controller-pod
neuvector-svc-controller          ClusterIP   None           <none>        18300/TCP,18301/TCP,18301/UDP   4h6m   app=neuvector-controller-pod
neuvector-svc-crd-webhook         ClusterIP   10.96.17.183   <none>        443/TCP                         4h6m   app=neuvector-controller-pod
```

**Comment by williamlin-suse** [comment]
I tried in on my local k8s & it works well.
Please get logs from all neuvector controllers & kube apiserver

**Comment by williamlin-suse** [comment]
Your pod runs as root by the configuration in the image, not in the pod resource.
When the image is not scanned, there is no way we can tell what's in the image.
That's why it doesn't get blocked on your env but it works well on my env.
Please create a registry entry for busybox in nv, scan it & try admission control again.

**Comment by LucasVanHaaren** [comment]
Wow okay I missed that !

I just added the DockerHub registry in `Assets > Registry` and filtered for `busybox` images : 

![image](https://user-images.githubusercontent.com/29121316/191970109-9db603c7-71be-4e44-924b-6f1031faf7bc.png)

Now it works as I expected :

```bash
kubectl run root-test --rm -it --image busybox -n rootless -- sh

Error from server: admission webhook "neuvector-validating-admission-webhook.neuvector.svc" denied the request: Creation of Kubernetes Pod is denied.
```

I'm so confused because I was thinking that running container images was automatically scanned but I just discovered that must be activated manually in configuration !

---

PS: I am also asking me about your last answer when you said "pod runs as root by the configuration in the image, not by the values in the pod resource". 
But I just tested to set a non-root `securityContext` to the same image and it won't be blocked. 
So I'm assuming nv still uses container runtime configuration (via `securityContext`) in order to block or not a root container and not only the image configuration that's right ?

**Comment by williamlin-suse** [comment]
Yes, we check both the k8s resource & image(if it's scanned).
To scan an image, we need to pull the image from the registry server & scan it. 
There is no guarantee how big the image size is or how fast the download speed is.
Considering admission control has time limit for the request handling, we decided not to to real-time image scanning.

**Comment by LucasVanHaaren** [comment]
Thank you so much for your help and explanation

**Comment by LucasVanHaaren** [comment]
Hey, after thinking about it I don't understand why is it mandatory to check for image configuration _(Image Scan criteria)_ in order to determine admission control policy compliance. 

Assuming an image built to run as root can be ran as non-root user and vice-versa via runtime config with Kubernetes securityContext, I think only container runtime configuration (_Deployment Yaml file scans criteria_) must be checked.
This way any container's pod can be enforced without the need of image scanning.

Is there anything I missed about this ?

**Comment by williamlin-suse** [comment]
Simply checking runtime configuration is not enough.
