### ISSUE TITLE
Cilium support

### ISSUE THREAD

**Issue by hwaastad** [neuvector/neuvector#45]
Hi, I’m trying out neuvector for different types of CNI’s.
Canal/Calico is working fine but I cannot get it to work using cilium.
After discovery, if I put a container in protected mode, traffic is blocked. Network rules are correct.
How could I debug this issue? Maybe ebpf related?

**Comment by gkosaka** [comment]
Keeping this open to track engineering progress with milestone

**Comment by gfsuse** [comment]
verified in protect mode the packet is dropped by cilium tc bpf, this is specifically related to our datapath in protect mode. 
next step I will try nfq(libnetfilter_queue) as a possible solution.

**Comment by gfsuse** [comment]
fixed by https://github.com/neuvector/neuvector/pull/247
closing the issue
