### ISSUE TITLE
ARM builds for docker images 

### ISSUE THREAD

**Issue by grinco** [neuvector/neuvector#451]
Hi, it would be great if you could add ARM64 architecture to the docker builds to be able to use them on power-efficient hardware, like the AWS Graviton offering.

**Comment by isaackuang** [comment]
+1 We also need use in AWS Graviton.

**Comment by wombelix** [comment]
+2 in https://github.com/neuvector/neuvector/issues/199
+1 in https://github.com/neuvector/neuvector/issues/131

**Comment by wombelix** [comment]
https://github.com/neuvector/neuvector/issues/199#issuecomment-1117527236
> Currently, ARM platform is not supported, especially because of the endianness issue in the network packets handling. We will put this in the roadmap based on the user requests.

@garyduan I would like to dive a little deeper on the actual technical requirements for an ARM build.

I interpret your comment, that the different network package handling is one of the largest blocker?

When we take a look at the NeuVector components - Controller (Rest API, config storage), Enforcer (applies security policies), Manager (Web UI), Scanner (image, container and host vulnerability scanning) and Updater (collects new CVE updates) - this would mean you refer to the Enforcer right? 

My understanding is, that the other components are not actively involved in anything related to network traffic scanning or handling?

Wouldn't that mean that for example Manager, Scanner and Updater should be not affected by ARM64 platform specifics and could cross-compiled? And that might also be the case for the Controller?

Why I'm asking this: Wouldn't it be an option to move to ARM64 support in multiple steps and start with potential low hanging fruits?

That would at least allow to run everything except the Enforcer in a ARM64 Cluster, for example a central management cluster, and from there to manage other NeuVector instances in a Multi-Cluster Setup?
Some slight difference in the supported feature set isn't new, for example when we compare Docker and Kubernetes deployments, so I have the felling during kind of a Alpha/Beta that would also be fine in case of ARM?
But sure, the highest value would have ARM support for all components for customers that want to go all in on ARM like with AWS Graviton instances.

I'm just thinking loud and looking forward to your thoughts on it, but for sure, every feedback from everyone interested in ARM64 support for NeuVector is welcome as well :)

**Comment by macmiranda** [comment]
For us, not having the enforcer is a deal breaker. All our workloads run on Graviton-based instances. Not being able to enforce security policies would make Neuvector become just another dashboard among many.

**Comment by becitsthere** [comment]
ARM based images will be released with 5.3.0, including all components.
