### ISSUE TITLE
Which CVE databases are used and how often are they updated in a running instance?

### ISSUE THREAD

**Issue by earthquakesan** [neuvector/neuvector#50]
Hello!

Could not find an answer to this question in the documentation. Which CVE databases are used in neuvector and how often are they pulled/updated in a running neuvector instance?

**Comment by becitsthere** [comment]
Scanner's is updated daily. Typically it is deployed as a kubernetes cronjob. Please refer to the deployment yaml file in the document. The image at neuvector/scanner.preview

**Comment by earthquakesan** [comment]
@becitsthere hi! Thanks for the answer!

I still could not find which CVE databases are used. By image do you mean docker image or there is an architecture diagram somewhere, which explains my question?

**Comment by gtam** [comment]
https://open-docs.neuvector.com/scanning/cve_sources#cve-database-sources

**Comment by earthquakesan** [comment]
Thanks a lot for the replies @gtam @becitsthere !
