### ISSUE TITLE
Can't load dashboard: Request is missing required HTTP header 'Token'

### ISSUE THREAD

**Issue by d4b0zz** [neuvector/neuvector#52]
Hi!

I'm running the preview version of neuvector (5.0.0) and deployed it on a RKE2 cluster via Rancher 2.6 charts (with modifications). All pods and services are running correctly with no errors.

I access the dashboard by clicking the service, I login with the default credentials and then read + accept the EULA. The dashboard almost fully loads and at the end it throws the following error (it's the only thing I can see):

`Request is missing required HTTP header 'Token'`

Console log:

`
DevTools failed to load source map: Could not load content for https://REDACTED_HOSTNAME/api/v1/namespaces/neuvector/services/https:neuvector-service-webui:8443/proxy/vendor-e8113a58f6b1c806aaf277cb2565c93e.map: HTTP error: status code 400, net::ERR_HTTP_RESPONSE_CODE_FAILURE

​ Uncaught SyntaxError: Unexpected token < in JSON at position 0

​ GET https://REDACTED_HOSTNAME/api/v1/namespaces/neuvector/services/https:neuvector-service-webui:8443/proxy/index.html/app/dashboard?v=7483daf7b7 400
`

Request that failed (there is around 10 tries for the same URL) copied as curl from browser network capture:

`curl "https://REDACTED_HOSTNAME/api/v1/namespaces/neuvector/services/https:neuvector-service-webui:8443/proxy/index.html/app/dashboard?v=7483daf7b7" ^
  -H "authority: REDACTED_HOSTNAME" ^
  -H "sec-ch-ua: ^\^" Not;A Brand^\^";v=^\^"99^\^", ^\^"Google Chrome^\^";v=^\^"97^\^", ^\^"Chromium^\^";v=^\^"97^\^"" ^
  -H "sec-ch-ua-mobile: ?0" ^
  -H "sec-ch-ua-platform: ^\^"Windows^\^"" ^
  -H "upgrade-insecure-requests: 1" ^
  -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" ^
  -H "accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9" ^
  -H "sec-fetch-site: same-origin" ^
  -H "sec-fetch-mode: navigate" ^
  -H "sec-fetch-dest: document" ^
  -H "referer: https://REDACTED_HOSTNAME/api/v1/namespaces/neuvector/services/https:neuvector-service-webui:8443/proxy/index.html?v=7483daf7b7" ^
  -H "accept-language: en-US,en;q=0.9" ^
  -H "cookie: R_PCS=light; R_LOCALE=en-us; R_THEME=dark; R_REDIRECTED=true; CSRF=d75778f767; R_SESS=token-xlzjh:kr27wfwr76qlmz2ncgh5d6fszgh47l2mj72fjv2wmzngwq579dpkz7" ^
  --compressed`

Response is a 400 Bad Request:

`cache-control: no-cache, private
content-length: 47
content-type: text/plain; charset=UTF-8
date: Thu, 03 Feb 2022 16:59:39 GMT
strict-transport-security: max-age=15724800; includeSubDomains
x-api-cattle-auth: true
x-content-type-options: nosniff`

I can't seem to get the ingress controller working to test it via ingress:

`
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["REDACTED_IP"],"port":443,"protocol":"HTTPS","serviceName":"neuvector:neuvector-service-webui","ingressName":"neuvector:nv-web-ui","hostname":"REDACTED_HOSTNAME","path":"/","allNodes":false}]'
  creationTimestamp: "2022-02-03T16:28:37Z"
  generation: 4
  managedFields:
  - apiVersion: networking.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:rules: {}
        f:tls: {}
    manager: rancher
    operation: Update
    time: "2022-02-03T16:28:37Z"
  - apiVersion: networking.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: nginx-ingress-controller
    operation: Update
    time: "2022-02-03T16:29:21Z"
  - apiVersion: extensions/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/publicEndpoints: {}
    manager: rancher
    operation: Update
    time: "2022-02-03T16:29:21Z"
  name: nv-web-ui
  namespace: neuvector
  resourceVersion: "19950782"
  uid: 2b408b8d-f18e-4896-9bc0-4bd051ddb160
spec:
  rules:
  - host: REDACTED_HOST
    http:
      paths:
      - backend:
          service:
            name: neuvector-service-webui
            port:
              number: 8443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - REDACTED_HOST
    secretName: nv-web-cert
status:
  loadBalancer:
    ingress:
    - ip: REDACTED_IP
`

Any clues on what might be wrong?
Thanks!

**Comment by BinX-Suse** [comment]
@d4b0zz, looks like you are using Rancher to launch NeuVector UI, is it? We are still working on the integration, map error is ok, the problem is that we are using absolute path, we have changed that part, but it's not in 5.0 branch yet, cause we have other issue to work on, will let you know once we have that ready.
