### ISSUE TITLE
make Gravatar support optional

### ISSUE THREAD

**Issue by pna-nca** [neuvector/neuvector#526]
**Is your feature request related to a problem? Please describe.**
When NeuVector is used in strict environments without Internet connectivity, accessing external resources may significantly slowdown the application rendering or produce artifacts.
In this particular case it also leads to leaking username to Gravatar. This is most likely not wanted behavior as in corporate use cases such usernames are usually purely technical.

**Describe the solution you'd like**
Ideally, it would be great to have an opportunity to globally disable Gravatar support via initcfg.yaml on deployment.

**Describe alternatives you've considered**
As an alternative I may suggest just disabling Gravatar completely as this feature is probably not widely used in corporate environments anyway.

**Additional context**
The function that is used to format Gravatar URL in current 5.0.4+ release: `getAvatar()`.
It is used in the following places:
- 4:profile-form.component.html
- 57:profile-form.component.ts
- 58:profile-form.component.ts
- 79:users-grid.component.ts

**Comment by becitsthere** [comment]
Thanks for the report. We will follow up on this request.

**Comment by rushk014** [comment]
As of v5.1.2, Gravatar can be enabled by setting manager env variable `GRAVATAR_ENABLED` (default `false`).
