### ISSUE TITLE
Can't access NeuVector WebUI in Rancher airgap

### ISSUE THREAD

**Issue by gingerjesus** [neuvector/neuvector#598]
Hi there!  I'm kinda new to Kubernetes but I know my way around the sysad world and Linux.  I'm currently having an issue getting NeuVector within Rancher to work.  I'm running Rancher 2.6.8 and RKE2 in an on-premises vSphere environment that is completely airgapped.  Everything runs fine and I'm able to publish sample apps to NodePort and I can get to them no problem.  I do have a layer 4 load balancer in front of my 3 master RKE2 server nodes that just allows 80 and 443 via NGINX. 

So I downloaded the NeuVector images for 5.1.0 (tagged/pushed internally), went to the apps/marketplace in Rancher and just filled in the bare minimum.  After the first page where you specify the images I changed the runtime to k3s containerd.  Only other thing I did was on the Service Configuration option I used Nodeport.  I clicked install and all the pods came online pretty quickly.  

Here's the two problems I'm running into:

If I click on the NeuVector option within Rancher to open the WebUI I get:  "error trying to reach service: dial tcp [cluster ip]:8443 connect:  connection refused".  reason "Service Unavailable".  code "503".

If I try the Nodeport:[Port] on any of my nodes it just times out.  I know there's nothing blocking ephemeral ports because like I said I have other apps using NodePort.

Which logs should I be looking at?  Describe and logs on the controller pods seem fine.  Thanks!

**Comment by becitsthere** [comment]
Please check if neuvector manager and controllers are running, and pull their log first.

**Comment by gingerjesus** [comment]
Everything was running but like I said I was new-ish to the environment and my original build was kind of clumsy.  I have since rebuilt on new RKE2 and Rancher 2.7.0 and 5.0.4 works fine out of the box.  Thanks!
