### ISSUE TITLE
Adding 5.1.0 images to Rancher helm chart garbles webui

### ISSUE THREAD

**Issue by gingerjesus** [neuvector/neuvector#623]
Hi there.

I just built a new RKE2 v1.24.7 along with Rancher 2.7.0 in a completely airgap environment.  I used the Apps & Marketplace in Rancher and using my private registry with the built-in 5.0.4 images it came right up.  It's truly an amazing product.   

So I went back into the App in Rancher and added the 5.1.0 images I downloaded and tagged in my private registry.  The controller, enforcer, and scanner all come up fine with 5.1.0.  It's when I add the manager 5.1.0 that the webUI becomes terribly garbled and I have to fallback to the 5.0.4 just for manager.  All the pods run fine even with 5.1.0 as manager.

Again, I'm new-ish to this so maybe there's a yaml value I have to change in Rancher since I imagine the partner chart won't be updated until a a new Rancher version.  I'm just now getting familiar with the partner charts and how they work.

This truly is an amazing product and management was truly impressed with all the features it comes with.  Thanks for any help!

**Comment by becitsthere** [comment]
Please try a few steps to see if the issues are fixed.
1. Only Chrome is officially supported.
2. Try incognito mode, if it works, try clear the browser cache
3. If all not working, please provide screenshots and manager and controller logs.

**Comment by becitsthere** [comment]
This is a known issue for the airgap environment, it is fixed in 5.1.1
