### ISSUE TITLE
DLP sensor name and rule name

### ISSUE THREAD

**Issue by hwaastad** [neuvector/neuvector#63]
Hi,
it seems there are some limitations to the sensor and rule name length:
sensor name: sensor.malicious.phpfile.upload
rule name: malicious.file.shell.exec.command
```
dpi_dlp_parse_opts_routine: Dlp rule((null)):(0) has invalid option(name : sensor.malicious.phpfile.upload_nvCtR.malicious.file.shell.exec.command)
```

If imposing limitations, the web gui should also have this limitations.
I am testing the https://developer.ibm.com/patterns/protect-your-web-application-using-advanced-runtime-container-security/
and saving rules does not work due to the "invalid option name"

I'm am running the 5.0.0 preview versions

**Comment by gfsuse** [comment]
this issue is fixed by PR https://github.com/neuvector/neuvector/pull/65
