### ISSUE TITLE
[Query] Do we have a Slack channel for community based discussions?

### ISSUE THREAD

**Issue by DilanUA** [neuvector/neuvector#653]
Folks, I am an open source enthusiast of your product and just wanted check if we do have a Slack channel or anything similar for community based discussions. Searched, but could not find any. If there isn't in fact any, I would suggest to start one as this could be really useful to foster a stronger sense of community among users and contributors and help build real-time communications with increased collaboration. Let me know of your thoughts. Best regards.

@garyduan @gkosaka

**Comment by gkosaka** [comment]
Please check out https://rancher-users.slack.com/archives/C036F6JDZ8C

**Comment by DilanUA** [comment]
Hey @gkosaka, It seems that I must have an account with the domain rancher.com or suse.com to login to this workspace. How should I proceed in that case? Thanks.

**Comment by gkosaka** [comment]
Please use this link to generate a self-invite: https://slack.rancher.io/

**Comment by DilanUA** [comment]
Thanks @gkosaka. I was just able to join "neuvector-security".
