### ISSUE TITLE
Usage of the agent

### ISSUE THREAD

**Issue by brness** [neuvector/neuvector#69]
I have read the docs about the neuvector and the architecture of the whole system, but according to the source code, besides the scanner, controller and upgrader, there is another component named agent which is not mentioned in the docs, so i wonder if someone can help me explain or show me some reference material about this part, I'll be appreciated.

**Comment by becitsthere** [comment]
Agent is the main component in the enforcer container, which also contains the data path binary, dp. Here is a section in Makefile,

```
    cp neuvector/monitor/monitor ${STAGE_DIR}/usr/local/bin/
    cp neuvector/agent/agent ${STAGE_DIR}/usr/local/bin/
    cp neuvector/agent/workerlet/pathWalker/pathWalker ${STAGE_DIR}/usr/local/bin/
    cp neuvector/dp/dp ${STAGE_DIR}/usr/local/bin/
```

This is where we copy these binaries and scripts into the folder to build the image.

**Comment by longpi1** [comment]
@becitsthere Hello, I do not understand some questions in reading the source code. What does DP mean? The flow of Engine? Is there any good documentation or code architecture diagrams that can help me quickly understand the source code for this project? so i wonder if someone can help me explain or show me some reference material about this part, I'll be appreciated.

**Comment by brness** [comment]
Thanks for your reply and your patience! @becitsthere For me, it's still sophisticated to understand the each part of the agent for such a huge amount of code, so would you mind sharing more stuff about the agent such as the primary functions or the logic flow diagram(I can see a lof of the fundamental socket programming code but don't know the purpose ). Maybe we can add a README file in each functional package to help more people get involved in, Thanks again!
