### ISSUE TITLE
Is there any architecture or design documentation for NeuVector?

### ISSUE THREAD

**Issue by longpi1** [neuvector/neuvector#76]
Hello, I recently wanted to know the source code of the project NeuVector, but I did not find the relevant architecture or documents that could help me quickly understand the source code of the project. Is there a good document or code architecture diagram that can help me quickly understand the source code of the project?I would appreciate it.

**Comment by chunyenlin** [comment]
No. Currently the document is unavailable.

**Comment by garyduan** [comment]
Product document is here https://open-docs.neuvector.com/.
