### ISSUE TITLE
Process profile rule not working for all members of a group

### ISSUE THREAD

**Issue by qdealfront** [neuvector/neuvector#787]
**Environment**
Platform: RKE2
Kubernetes/Platform Version(s): v1.24.7+rke2r1 and NeuVector v5.1.2

**Describe the bug**
We have created a custom group containing containers of two namespaces. This group has a process profile rule to allow everything. This works for containers for one of the two namespaces, but for containers of the second namespace we still get security events. 

**To Reproduce**
1. Go to 'Policy'
2. Go to 'Groups'
3. Create a group with two namespaces (as criteria)
4. Add a process profile rule to that group that allows everything (*, *)
5. Go to 'Notifications'
6. Go to 'Security Events'
7. No security events for one of the namespaces get added, but we still get new security events for the second namespace. 
8. Even if we click on 'Review Rule' and try adding the rule manually, we still get new security events for the second group. 

**Expected behavior**
No new security events for any of the two namespaces get added anymore. 

**Additional context**
When checking the members of the group in the Groups-tab we can see containers from both namespaces, so the group seems to know all the members it should have. 
Also, we have not touched the automatically created groups.

**Comment by becitsthere** [comment]
Thanks for reporting the issue. We will look into it.

**Comment by qdealfront** [comment]
Hi @jaimeyu-suse, 
I have made some screenshots of our system. Is that the configuration you were looking for or is there anything else you need to understand the problem better?

The group we use for testing: 
![groups1](https://github.com/neuvector/neuvector/assets/132365594/e09b7587-745b-4270-80d9-6f29d0d14f18)

The criteria of the group:
![groups2](https://github.com/neuvector/neuvector/assets/132365594/cf271a8a-de65-4947-90d1-b06cc5bab47a)

-> as members of both namespaces are listed in the group we assume that the group was created correctly

The process profile rule (everything allowed for testing purposes):
![groups3](https://github.com/neuvector/neuvector/assets/132365594/d754b400-753f-40f0-999d-a8e349b417dc)

But we still get security alerts for one of the namespaces (only for one though, it seems to be working for the other namespace):
![groups4](https://github.com/neuvector/neuvector/assets/132365594/8be61256-0b19-4768-a73e-9ec365886d18)

Thanks for looking into it!

**Comment by jaimeyu-suse** [comment]
Hi @ qdealfront,

I could not reproduce it with my own 4 node rke2 cluster and minikube; nor can my colleague with his setup. I asked around and we're suspecting the issue might be that the pod isn't actually part of the namespace for some reason. So one thing to check is to go to the UI and bring up the custom group and verify the pods are showing up there. If they're not, then that's probably why its not working. 
Here is what it looks like on my testbed.
![Screenshot 2023-05-12 at 1 28 08 PM](https://github.com/neuvector/neuvector/assets/115037071/34bd94a4-bd56-49fc-bfc2-c739368b935e)

We would need some logs to dig deeper down since we cannot reproduce it. 

So I think for actions for you:
1. Verify the pods and containers are part of the custom group
2. Logs if possible (see 3)
3. Reproduce in a different setup which would also help if you can share the setup details so we can reproduce it. 

Finally, I'm not sure if you are familiar with our CLI interface but you can use it to debug it as well.
```
show container profile-process <container id>
Example:
admin#127.0.0.1> show container profile-process e6fd

+-------+---------------+--------+--------------+------------+
| name  | path          | action | type         | group      |
+-------+---------------+--------+--------------+------------+
| bash  | /usr/bin/bash | allow  | learned      | nv.ubuntu  |
| hello | /bin/hello    | allow  | user created | containers |
+-------+---------------+--------+--------------+------------+
```
which can also tell you/us which group the process belongs to.

**Comment by qdealfront** [comment]
Hi @jaimeyu-suse, 

thanks for your response and the time you have put into this problem. 

1. From what we can see in the UI the custom group should be populated correctly. 
2. I will attach a screenshot with the requested information below:
![grafik](https://github.com/neuvector/neuvector/assets/132365594/96f940a8-1675-4abf-be7d-a80cd5b0671f)
The way we understand it everything should work as expected. The ID belongs to the *****pod2 (third line from the bottom), which is also the one mentioned in the alert. The way we see it is even allowed twice: once by the custom group and then also by the rule of the automatically created group. 
![grafik](https://github.com/neuvector/neuvector/assets/132365594/051ed64d-fec6-4ea8-a03c-01d6827de07e)

Does this information help? Is there any other information we can add? 

Thanks!

**Comment by jaimeyu-suse** [comment]
Hi @qdealfront - I discussed with some colleagues and want to know how you are executing the `curl` command?

It's being reported as an external process and did you install after starting up the container or such?

**Comment by qdealfront** [comment]
Hi @jaimeyu-suse, 

curl got installed after the container started via apt. It's the same for the other container in the other namespace though...

**Comment by jaimeyu-suse** [comment]
Hi, that's what we think was happening. Can you check that ZERO DRIFT is not enabled. If it is, please disable ZERO DRIFT? 

> Zero-drift process and file protection. This is the new default mode for process and file protections. Zero-drift automatically allows only processes which originate from the parent process that is in the original container image, and does not allow file updates or new files to be installed. When in Discover or Monitor mode, zero-drift will alert on any suspicious process or file activity. In Protect mode, it will block such activity. Zero-drift does not require processes to be learned or added to an allow-list. Disabling zero-drift for a group will cause the process and file rules listed for the group to take effect instead.
https://newreleases.io/project/github/neuvector/neuvector/release/v5.0.0

See further details here https://open-docs.neuvector.com/policy/processrules#zero-drift-process-protection

**Comment by qdealfront** [comment]
Hi @jaimeyu-suse, 

sorry for getting back to you so late and thanks for the response. 
So far we hadn't really looked into ZERO-DRIFT, but that's exactly what was wrong. After having disabled it, we are not getting unwanted alerts anymore. 

I do have a question about this topic tho:
In the manual (https://open-docs.neuvector.com/policy/processrules#zero-drift-process-protection) there's additional information about zero drift: 

> NOTE: **The process/file rules listed for each group are always applied, even when zero-drift is enabled**. This offers a way to add allow/deny exceptions to the base zero-drift protections. Keep in mind that if a group starts in Discover mode, process/file rules can be automatically added to the list, and should be reviewed and edited before moving to Monitor/Protect modes.

Reading this note makes me really confused, cause to me it sounds like the process rules list is applied even when zero-drift is enabled. This contradicts the paragraph above and also the experience that the list is being ignored. So now I don't really know what to believe anymore. Mabe you can help me understand? 

Thanks!

**Comment by jaimeyu-suse** [comment]
Hi, That's wonderful to hear. I will close the ticket soon!

As for your concern, they're not mutually exclusive rulesets. If you're not in ZD mode, you're protected through the black/whitelist process rules. Discover mode lets you quickly create ALLOW rules automatically. 

When you're in ZD, extra protections are done as well as respecting the black/whitelists.  If you set it up immediately into ZD mode with no white/black list. You will be protected through the image scanner and it will look for suspicious processes and newly introduced files. If you're not in ZD mode, it doesn't do the extra scans (generally ZD allows you set and forget while non ZD requires you to setup your black/whitelists).  

If you have a white/black list and ZD enabled. The black/whitelist supercede the ZD rules. So if you know you're going to be installing applications thru apt and not already existing in the base image, you can add an ALLOW rule for that binary which will let it work in both ZD and non-ZD mode. 

I hope I explained it well enough but if I haven't, please contact support@neuvector.com for more information about best practices and uses of the product. I'm sure our QA and Sales people have a lot of tips about how to best configure Neuvector that I'm not aware of.
