### ISSUE TITLE
Negative score improvement suggested

### ISSUE THREAD

**Issue by qdealfront** [neuvector/neuvector#788]
**Environment**
Platform: RKE2
Kubernetes/Platform Version(s): v1.24.7+rke2r1 and NeuVector v5.1.2

**Describe the bug**
When trying to improve our score, we get suggestions that would make our score worse. 

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Improve your score'
3. Click on 'Review Ingress/Egress related network policy rules or actions. '
4. The Projected score improvement is worsening our score. 

**Expected behavior**
Only suggestions to improve the score should be made. 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/132365594/236156560-b7283316-6422-47bb-9472-82ae993dcab5.png)

**Comment by becitsthere** [comment]
Thanks for reporting the issue, we are working on this.

**Comment by becitsthere** [comment]
Will be fixed in 5.1.3 release
