### ISSUE TITLE
Option to change the order of Admission control rules

### ISSUE THREAD

**Issue by qdealfront** [neuvector/neuvector#789]
**Is your feature request related to a problem? Please describe.**
Because the order of the rules in 'Admission control' matters (as they are evaluated top to bottom) it would be great to have an option to change the order of these rules. It frustrates me when I want to add a rule that should get evaluated before the already existing rules but there is not way to add the new rule on top of the old ones. 

**Describe the solution you'd like**
It would be nice to have an option to change the order of the rules either via drag-and-drop, changing the rule ids, ...

**Describe alternatives you've considered**
Alternatively you could delete all rules, add the new rule on top and then add all the old rules again, but this is annoying, time consuming and allows errors. So we don't actually wanna do it this way.

**Comment by williamlin-suse** [comment]
For admission control rules, the matching order is:
1. default allow rules
2. fed allow rules (if exist)
3. fed deny rules (if exist)
4. CRD allow rules (if exist)
5. CRD deny rules (if exist)
6. user-defined allow rules
7. user-defined deny rules
8. allow the request if the request doesn't match any rule's criteria
In each of the matching stages(1~7), rules order doesn't matter. 
As long as the request matches one rule's criteria, the action(allow or deny) is taken & the request is allowed or denied

**Comment by qdealfront** [comment]
Hey, thanks for clarifying. It seems like I should have read the documentation more carefully.
