### ISSUE TITLE
enforce container exit with error “Failed to initialize - error=Unknown container runtime” 

### ISSUE THREAD

**Issue by x-coder-L** [neuvector/neuvector#79]
Hi!
when I use helm to install neuvector(version 1.8.8),I met this issue that container can not run .
the image I used:
neuvector/controller.preview:5.0.0-preview.1
neuvector/manager.preview:5.0.0-preview.1
neuvector/scanner.preview:latest
neuvector/enforcer.preview:5.0.0-preview.1
neuvector/updater.preview:latest
![image](https://user-images.githubusercontent.com/62658324/154418394-bf7c0b56-e676-4615-b773-6c89bd03b0c8.png)

**Comment by becitsthere** [comment]
What container runtime does the node have and what do you choose in the helm chart?

**Comment by x-coder-L** [comment]
> What container runtime does the node have and what do you choose in the helm chart?

Thanks! I changed the container runtime in value.yaml. and all the pod is running now.
