### ISSUE TITLE
LDAP/AD Authenticated Users Unable to Give Namespaced Access to Role

### ISSUE THREAD

**Issue by rparke** [neuvector/neuvector#81]
We are wanting to run neuvector on a multi-tenancy Kubernetes cluster using Active Directory to authenticate users and construct a specific role for them which gives them read access to runtime scanning of objects just in their namespace.

This is possible if we manually create a user using the web ui:
<img width="1152" alt="Screenshot 2022-02-18 at 11 14 56" src="https://user-images.githubusercontent.com/50015370/154672440-f0c41342-acfc-4cea-8039-d23b78480f8f.png">

If a user is created using integration with AD no such option is available. We are only permitted to set a Global role:

<img width="1158" alt="Screenshot 2022-02-18 at 11 17 00" src="https://user-images.githubusercontent.com/50015370/154672844-9a726920-87dc-457c-9b5d-8c99843949d6.png">

**Comment by BinX-Suse** [comment]
You can use Settings/LDAP/AD Settings to set the role, note we only support AD group, you can set the role there and add the users into that group.
![image](https://user-images.githubusercontent.com/96315730/154742753-beb61931-acdb-420a-ab03-53b81325b929.png)

<img width="1321" alt="Screen Shot 2022-02-18 at 10 36 28 AM" src="https://user-images.githubusercontent.com/96315730/154742778-f4a4f53e-4b2a-4146-89f2-409aafe97fa4.png">
