### ISSUE TITLE
Private registries limits (repo and tag)

### ISSUE THREAD

**Issue by theobori** [neuvector/neuvector#853]
Hi,

I noticed that the repository limit (repo_limit) and tag limit (tag_limit) were not applied for private registries. So I went to read the code and it seems like it has been implemented for public registries only.

I'd just like to know if this is a choice or if the implementation is missing?

**Comment by becitsthere** [comment]
You are right. This only applies to docker public registry, to limit number of images to be scanned. Other registries don't have this limit.
