### ISSUE TITLE
What's the role of Consul in NeuVector?

### ISSUE THREAD

**Issue by brness** [neuvector/neuvector#89]
I can see a lot config about Consul in the source code of Controller, and the logs show that Controller did initialize with the process of Consul set up. All i know is Consul is a open source project which works in service discover and service registry, so what's the relationship between agent in Consul and controller in NeuVector? And how NeuVector make use of the Consul to achieve what kind of purpose?

**Comment by chunyenlin** [comment]
NeuVector makes use of Consul mainly for key value store & leader election.

**Comment by longpi1** [comment]
> NeuVector makes use of Consul mainly for key value store & leader election.

How does neuvector handle events in protected mode? No specific code was found

**Comment by chunyenlin** [comment]
What's the issue?

**Comment by longpi1** [comment]
> What's the issue?

Is there any good architecture diagram or documentation for me to read the source code better? I read the source code with a lot of confusion

**Comment by chunyenlin** [comment]
Currently the document is unavailable

**Comment by brness** [comment]
@chunyenlin  Thank your for your reply? But after I read the main function of Controller, there are some question:
What's the main purpose of controller/kv/conig.go ? Because I can see the kv.init() with a start of newConfigHelper

> func 

    func newConfigHelper(id, version string, persist bool) ConfigHelper {
      c := new(configHelper)
	  c.id = id
	  c.version = version
	  c.persist = persist
	  c.backupTimer = time.NewTimer(backupDelayIdle)
	  c.backupTimer.Stop()
	  c.cfgChanged = utils.NewSet()
	  c.startBackupThread()
	  cfgHelper = c
	  return c}

but the startBackUpThread() make me confuse? Why we need this step?
