### ISSUE TITLE
[UI] Cannot change default password

### ISSUE THREAD

**Issue by kenankule** [neuvector/neuvector#91]
Default password for the admin user is 5 characters, `admin`
Default password profile requires min 6 characters.
When I try to change the default password from the manager, UI "validates" the current password against the password profile and gives an error and the "Update Profile" button is grayed out.
>  6 character(s) minimum. 

Workaround: Update the password profile to accept 5 characters.

I'd recommend, either change the default password profile, or disable the form validation for the `Current Password` field in `Edit Profile` view. I believe the form should not validate the current password before it is sent to server.

**Comment by BinX-Suse** [comment]
Thanks, I think we shouldn't validate the current password while edit profile.

**Comment by rushk014** [comment]
@kenankule There isn't any client input validation for the `Current Password` field, only for the `New Password` (and `Confirm New Password`), so there shouldn't be any issue changing the default password from `admin` to something else. The only reason "Update Profile" should be grayed out is if the `New Password` fails input validation (eg. "password does not match").

> 6 character(s) minimum.

This refers to the password format requirements for new passwords only, which you can modify for local user accounts under "Settings > Users & Roles > Password Format Requirement".
<img width="1512" alt="Screen Shot 2022-02-28 at 4 05 04 PM" src="https://user-images.githubusercontent.com/29556139/156079945-2700323c-939b-4eb9-8f72-2524cb025ca8.png">
Please let me know if this clears anything up.

**Comment by kenankule** [comment]
Sorry, I think the problem was different. Its a corner case.

In the Edit Profile view, if you enter "New Password" and "Confirm New Password" fields correctly(according to the policy), but "Current Password" field incorrectly and hit "Update Profile" you get an error "Current Password Doesn't Match". Then the form reports "6 character(s) minimum" and never comes back to a healthy state.
