### ISSUE TITLE
Updater can not update successful

### ISSUE THREAD

**Issue by freeit001** [neuvector/neuvector#93]
Hi
I try to update neuvector CVE DB,but can not successful, updater cron job prompt :
ImagePullBackOff and ErrImagePull
The events as following:
Events:
  Type     Reason     Age                 From                         Message
  ----     ------     ----                ----                         -------
  Normal   Scheduled  2m                                               Successfully assigned neuvector/neuvector-updater-pod-1645902120-fsrzj to node01.localdomain
  Warning  Failed     119s                kubelet, node01.localdomain  Failed to pull image "registry.neuvector.com/updater": rpc error: code = Unknown desc = Error response from daemon: Get https://registry.neuvector.com/v2/: read tcp 192.168.2.161:58592->34.120.39.14:443: read: **connection reset by peer**
  Warning  Failed     104s                kubelet, node01.localdomain  Failed to pull image "registry.neuvector.com/updater": rpc error: code = Unknown desc = Error response from daemon: Get https://registry.neuvector.com/v2/: read tcp 192.168.2.161:58650->34.120.39.14:443: read: **connection reset by peer**
  Warning  Failed     69s                 kubelet, node01.localdomain  Failed to pull image "registry.neuvector.com/updater": rpc error: code = Unknown desc = Error response from daemon: Get https://registry.neuvector.com/v2/updater/manifests/latest: Get https://registry.neuvector.com/_token?scope=repository%3Aupdater%3Apull: read tcp 192.168.2.161:58746->34.120.39.14:443: read: connection reset by peer
  Normal   Pulling    23s (x4 over 119s)  kubelet, node01.localdomain  Pulling image "registry.neuvector.com/updater"
  Warning  Failed     21s (x4 over 119s)  kubelet, node01.localdomain  Error: ErrImagePull
  Warning  Failed     21s                 kubelet, node01.localdomain  **Failed to pull image "registry.neuvector.com/updater": rpc error: code = Unknown desc = Error response from daemon: Get** https://registry.neuvector.com/v2/updater/manifests/latest: denied: Permission "artifactregistry.repositories.downloadArtifacts" denied on resource "projects/neuvector-cloud-live-292322/locations/us/repositories/neuvector-us" (or it may not exist)
  Normal   BackOff    10s (x6 over 118s)  kubelet, node01.localdomain  Back-off pulling image "registry.neuvector.com/updater"
  Warning  Failed     10s (x6 over 118s)  kubelet, node01.localdomain  **Error: ImagePullBackOff**

**Comment by gtam** [comment]
The error suggest permission issues against registry.neuvector.com.  Registry.neuvector.com is a private registry.  For the preview images, you will need to point to the preview images listed in the README.

**Comment by garyduan** [comment]
You can point to neuvector/scanner.preview:latest for the scanner images. It is API compatible with the GA releases.
