### ISSUE TITLE
Neuvector docs redirecting to suse website

### ISSUE THREAD

**Issue by rammanoj** [neuvector/neuvector#940]
The https://open-docs.neuvector.com/ seems to be inaccessible. It is getting redirected to https://www.suse.com/neuvector/. I could not find any docs over there as well!

**Comment by dimitarzahariev** [comment]
The issue with the documentation has been sorted out.

**Comment by rammanoj** [comment]
Thanks @dimitarzahariev is there any specific reason for the redirection?
