### ISSUE TITLE
Webhook over corporate proxy

### ISSUE THREAD

**Issue by 0Styless** [neuvector/neuvector#984]
**Environment**
Platform: Kubernetes Rancher / RKE2
Kubernetes/Platform Version(s): v1.25.11+rke2r1
OS: SLES15-SP4
NeuVector Version: 5.2.1 / 2.6.2

**Describe the bug**
We run NeuVector on-premise behind a corporate proxy. If we try to send Webhooks (for example to MS Teams) they never arrive.
The same Webhooks to an internal endpoint will be sent as expected.

Proxy configuration in NeuVector >> Settings is activated. We can't see any errors in the log files. Is it possible to send Webhooks over a proxy instance?

**To Reproduce**
1. Deploy NeuVector in air gapped environment / behind a corporate proxy
2. Configure proxy settings in NeuVector
3. Create a Webhook for an external endpoint (e.g. MS Teams)
4. Create a Response Rule with the Webhook
5. Trigger the Response Rule

**Expected behavior**
Webhooks / Response Rule messages arrive as expected.

**Comment by glovecchi0** [comment]
The "Support webhooks through a proxy" feature has been added since NeuVector version 5.3.0.

https://open-docs.neuvector.com/releasenotes/5x#530-february-2024
